In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import date
from datetime import timedelta
import statistics as stats
import warnings
%matplotlib inline
plt.style.use('ggplot')


pd.set_option('display.max_columns', 500)
pd.set_option('display.max_colwidth', 500)
pd.set_option('display.max_info_columns', 500)
pd.set_option('display.max_info_rows', 2000)
pd.set_option('display.expand_frame_repr', True)
pd.set_option('display.width', 2000)


warnings.filterwarnings("ignore")
warnings.warn("this will not show")

In [2]:
# Loading data
oto = pd.read_json("scout_car.json", orient = "records", lines = True)
## second way: 
#  oto = pd.read_json("C:/Users/smdkc/Desktop/DS/Proje_ExploratoryDataAnalysis_EDA/scout_car.json", 
#                   lines=True)

In [3]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration         prev_owner  kW      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty                      Full Service   Non-smoking Vehicle null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery              Body Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders          Weight  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016  2 previous owners NaN   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]                          [\n, \n]              [\n, \n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]  [\n, Sedans, \n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]   [\n3\n]  [\n1,220 kg\n]  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017               None NaN  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN                               NaN                   NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]

## Now let's try to examine our dataframe (oto)

In [4]:
oto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15919 entries, 0 to 15918
Data columns (total 54 columns):
 #   Column                         Dtype  
---  ------                         -----  
 0   url                            object 
 1   make_model                     object 
 2   short_description              object 
 3   body_type                      object 
 4   price                          int64  
 5   vat                            object 
 6   km                             object 
 7   registration                   object 
 8   prev_owner                     object 
 9   kW                             float64
 10  hp                             object 
 11  Type                           object 
 12  Previous Owners                object 
 13  Next Inspection                object 
 14  Inspection new                 object 
 15  Warranty                       object 
 16  Full Service                   object 
 17  Non-smoking Vehicle            object 
 18  null  

In [5]:
oto.describe()

price   kW
count  15919.000000  0.0
mean   18019.896727  NaN
std     7386.169409  NaN
min       13.000000  NaN
25%    12850.000000  NaN
50%    16900.000000  NaN
75%    21900.000000  NaN
max    74600.000000  NaN

In [6]:
oto.shape

(15919, 54)

In [7]:
# Checking missing value counts of each column
oto.isnull().sum()

url                                  0
make_model                           0
short_description                   46
body_type                           60
price                                0
vat                               4513
km                                   0
registration                         0
prev_owner                        6828
kW                               15919
hp                                   0
Type                                 2
Previous Owners                   6640
Next Inspection                  12384
Inspection new                   11987
Warranty                          5420
Full Service                      7704
Non-smoking Vehicle               8742
null                                 0
Make                                 0
Model                                0
Offer Number                      3175
First Registration                1597
Body Color                         597
Paint Type                        5772
Body Color Original      

## Identifying the amount of the Missing Values

In [8]:
oto.shape[0]

15919

In [9]:
oto.isnull().sum()*100/oto.shape[0]

url                                0.000000
make_model                         0.000000
short_description                  0.288963
body_type                          0.376908
price                              0.000000
vat                               28.349771
km                                 0.000000
registration                       0.000000
prev_owner                        42.892141
kW                               100.000000
hp                                 0.000000
Type                               0.012564
Previous Owners                   41.711163
Next Inspection                   77.793831
Inspection new                    75.299956
Warranty                          34.047365
Full Service                      48.395000
Non-smoking Vehicle               54.915510
null                               0.000000
Make                               0.000000
Model                              0.000000
Offer Number                      19.944720
First Registration              

In [10]:
col_list = list(oto.columns)

In [11]:
col_list

['url',
 'make_model',
 'short_description',
 'body_type',
 'price',
 'vat',
 'km',
 'registration',
 'prev_owner',
 'kW',
 'hp',
 'Type',
 'Previous Owners',
 'Next Inspection',
 'Inspection new',
 'Warranty',
 'Full Service',
 'Non-smoking Vehicle',
 'null',
 'Make',
 'Model',
 'Offer Number',
 'First Registration',
 'Body Color',
 'Paint Type',
 'Body Color Original',
 'Upholstery',
 'Body',
 'Nr. of Doors',
 'Nr. of Seats',
 'Model Code',
 'Gearing Type',
 'Displacement',
 'Cylinders',
 'Weight',
 'Drive chain',
 'Fuel',
 'Consumption',
 'CO2 Emission',
 'Emission Class',
 '\nComfort & Convenience\n',
 '\nEntertainment & Media\n',
 '\nExtras\n',
 '\nSafety & Security\n',
 'description',
 'Emission Label',
 'Gears',
 'Country version',
 'Electricity consumption',
 'Last Service Date',
 'Other Fuel Types',
 'Availability',
 'Last Timing Belt Service Date',
 'Available from']

## Let's begin to implement EDA Process to all columns

#### We'll begin with the variables which has high percentage of missing values(NaNs).

#### We can remove some of them. At the begining we can focus on the columns that have %35 precentage and higher of missing values

In [12]:
def show_nans(oto, limit):
    missing = oto.isnull().sum()*100/oto.shape[0]
    return missing.loc[lambda x : x > limit]
show_nans(oto, 35)

prev_owner                        42.892141
kW                               100.000000
Previous Owners                   41.711163
Next Inspection                   77.793831
Inspection new                    75.299956
Full Service                      48.395000
Non-smoking Vehicle               54.915510
Paint Type                        36.258559
Model Code                        68.729192
Cylinders                         35.680633
Weight                            43.809285
Drive chain                       43.080596
Emission Label                    74.967021
Country version                   52.346253
Electricity consumption           99.139393
Last Service Date                 96.444500
Other Fuel Types                  94.472015
Availability                      96.011056
Last Timing Belt Service Date     99.899491
Available from                    98.291350
dtype: float64

We can drop the columns which have 90 percentage or high of missing values.
'Availability', 'Available from', 'Electricity consumption', 'Last Service Date', 'Last Timing Belt Service Date', 'Other Fuel Types', 'kW'

In [13]:
drop_list1 = ['Availability','Available from','Electricity consumption','Last Service Date',
              'Last Timing Belt Service Date', 'Other Fuel Types','kW']

In [14]:
oto.drop(drop_list1, axis=1, inplace=True)

### "prev_owner" and "Previous Owners"

In [15]:
oto[["prev_owner", "Previous Owners"]]

prev_owner                                                                            Previous Owners
0      2 previous owners                                                                                      \n2\n
1                   None                                                                                        NaN
2       1 previous owner                                                                                      \n1\n
3       1 previous owner                                                                                      \n1\n
4       1 previous owner                                                                                      \n1\n
...                  ...                                                                                        ...
15914               None                                                                                        NaN
15915   1 previous owner  [\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]
15916   1 previous owner                                                           [\n1\n, \n139 g CO2/km (comb)\n]
15917               None                                                                                        NaN
15918   1 previous owner                                                                                      \n1\n

[15919 rows x 2 columns]

In [16]:
# Examining prev_owner column
print('Checking prev_owner column')
print('--------------------------')
print(oto['prev_owner'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['prev_owner'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['prev_owner'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['prev_owner'].dtype,'\n\n')

Checking prev_owner column
--------------------------
0        2 previous owners
1                     None
2         1 previous owner
3         1 previous owner
4         1 previous owner
               ...        
15914                 None
15915     1 previous owner
15916     1 previous owner
15917                 None
15918     1 previous owner
Name: prev_owner, Length: 15919, dtype: object 


Number of each values
--------------------------
1 previous owner     8294
NaN                  6828
2 previous owners     778
3 previous owners      17
4 previous owners       2
Name: prev_owner, dtype: int64 


Number of missing values
--------------------------
6828 


Data type
--------------------------
object 




In [17]:
oto["prev_owner"] = oto["prev_owner"].str.replace(" previous owner", "").str.replace("s", "")

In [18]:
oto.prev_owner.value_counts(dropna = False)

1      8294
NaN    6828
2       778
3        17
4         2
Name: prev_owner, dtype: int64

In [19]:
oto["prev_owner"].fillna(method='bfill', inplace=True)

In [20]:
oto.prev_owner.value_counts(dropna = False)

1    14692
2     1187
3       38
4        2
Name: prev_owner, dtype: int64

In [21]:
# Examining Previous Owners column
print('Checking Previous Owners column')
print('--------------------------')
print(oto['Previous Owners'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Previous Owners'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Previous Owners'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Previous Owners'].dtype,'\n\n')

Checking Previous Owners column
--------------------------
0                                                                                            \n2\n
1                                                                                              NaN
2                                                                                            \n1\n
3                                                                                            \n1\n
4                                                                                            \n1\n
                                                   ...                                            
15914                                                                                          NaN
15915    [\n1\n, \n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]
15916                                                             [\n1\n, \n139 g CO2/km (comb)\n]
15917                                             

In [22]:
oto['Previous Owners'].str.strip("\n")

0          2
1        NaN
2          1
3          1
4          1
        ... 
15914    NaN
15915    NaN
15916    NaN
15917    NaN
15918      1
Name: Previous Owners, Length: 15919, dtype: object

In [23]:
oto['Previous Owners'].str.strip("\n").value_counts(dropna=False)

1      8101
NaN    6870
2       766
0       163
3        17
4         2
Name: Previous Owners, dtype: int64

In [24]:
oto['Previous Owners'].str[0]

0           \n
1          NaN
2           \n
3           \n
4           \n
         ...  
15914      NaN
15915    \n1\n
15916    \n1\n
15917      NaN
15918       \n
Name: Previous Owners, Length: 15919, dtype: object

In [25]:
oto['Previous Owners'].str[0].str[1]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
15914    NaN
15915      1
15916      1
15917    NaN
15918    NaN
Name: Previous Owners, Length: 15919, dtype: object

In [26]:
oto['Previous Owners'].str[0].str[1].value_counts(dropna=False)

# those values(0,1,2) are not visible in previous format

NaN    15689
1        193
0         25
2         12
Name: Previous Owners, dtype: int64

In [27]:
oto["Previous_Owner1"] = oto['Previous Owners'].str[0].str[1]
oto["Previous_Owner1"]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ... 
15914    NaN
15915      1
15916      1
15917    NaN
15918    NaN
Name: Previous_Owner1, Length: 15919, dtype: object

In [28]:
oto['Previous_Owner'] = oto['Previous Owners'].str.strip('\n')
oto['Previous_Owner']

0          2
1        NaN
2          1
3          1
4          1
        ... 
15914    NaN
15915    NaN
15916    NaN
15917    NaN
15918      1
Name: Previous_Owner, Length: 15919, dtype: object

In [29]:
oto.Previous_Owner.fillna(oto.Previous_Owner1, inplace=True)
oto.Previous_Owner.value_counts(dropna=False)

1      8294
NaN    6640
2       778
0       188
3        17
4         2
Name: Previous_Owner, dtype: int64

In [30]:
oto["Previous_Owner"].fillna(method='bfill', inplace=True)

In [31]:
oto["Previous_Owner"].value_counts(dropna = False)

1    14169
2     1179
0      531
3       38
4        2
Name: Previous_Owner, dtype: int64

##### It's better to drop "prev_owner" column in order to benefit more from "Previous_Owner". By the way, It is time to drop the other useless columns : "Weight", 'Non-smoking Vehicle'.

In [32]:
drop_list2 = ["prev_owner", 'Weight','Non-smoking Vehicle']

In [33]:
oto.drop(drop_list2, axis = 1, inplace = True)

##### 'body_type' is also very similar to 'Body'.

In [34]:
def fill_most(oto, group_col, col_name):
    for group in list(oto[group_col].unique()) :
        grp_inx = list(oto[oto[group_col] == group][col_name].index)
        oto[col_name].iloc[grp_inx] = oto[col_name].iloc[grp_inx].fillna(oto[oto[group_col] == group][col_name].mode()[0])

In [35]:
oto["body_type"].value_counts(dropna = False)

Sedans           7903
Station wagon    3553
Compact          3153
Van               783
Other             290
Transporter        88
NaN                60
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [36]:
oto.groupby("make_model")["body_type"].value_counts(dropna = False)

make_model      body_type    
Audi A1         Sedans           1538
                Compact          1039
                Station wagon      21
                Other              13
                Coupe               2
                Van                 1
Audi A2         Off-Road            1
Audi A3         Sedans           2598
                Station wagon     282
                Compact           182
                Other              16
                Convertible         8
                NaN                 7
                Coupe               4
Opel Astra      Station wagon    1211
                Sedans           1053
                Compact           185
                Other              67
                NaN                 7
                Coupe               2
                Off-Road            1
Opel Corsa      Compact          1230
                Sedans            875
                Other              87
                Coupe              13
                Tran

In [37]:
fill_most(oto, "make_model", "body_type")

In [38]:
oto.body_type.value_counts(dropna = False)

Sedans           7925
Station wagon    3563
Compact          3155
Van               809
Other             290
Transporter        88
Off-Road           56
Coupe              25
Convertible         8
Name: body_type, dtype: int64

In [39]:
# Examining Body column
print('Checking Body column')
print('--------------------------')
print(oto['Body'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Body'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Body'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Body'].dtype,'\n\n')

Checking Body column
--------------------------
0        [\n, Sedans, \n]
1        [\n, Sedans, \n]
2        [\n, Sedans, \n]
3        [\n, Sedans, \n]
4        [\n, Sedans, \n]
               ...       
15914       [\n, Van, \n]
15915       [\n, Van, \n]
15916       [\n, Van, \n]
15917       [\n, Van, \n]
15918       [\n, Van, \n]
Name: Body, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n, Sedans, \n]           7903
[\n, Station wagon, \n]    3553
[\n, Compact, \n]          3153
[\n, Van, \n]               783
[\n, Other, \n]             290
[\n, Transporter, \n]        88
NaN                          60
[\n, Off-Road, \n]           56
[\n, Coupe, \n]              25
[\n, Convertible, \n]         8
Name: Body, dtype: int64 


Number of missing values
--------------------------
60 


Data type
--------------------------
object 




In [40]:
oto.drop("Body", axis = 1, inplace = True) # no need Body column. use the body_type instead of it.

##### 'Inspection new'

In [41]:
# Examining Inspection new column
print('Checking Inspection new column')
print('--------------------------')
print(oto['Inspection new'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Inspection new'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Inspection new'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Inspection new'].dtype,'\n\n')

Checking Inspection new column
--------------------------
0                     [\nYes\n, \nEuro 6\n]
1                                       NaN
2                                       NaN
3                                       NaN
4        [\nYes\n, \n109 g CO2/km (comb)\n]
                        ...                
15914                                   NaN
15915                                   NaN
15916           [\nYes\n, \nEuro 6d-TEMP\n]
15917                                   NaN
15918    [\nYes\n, \n153 g CO2/km (comb)\n]
Name: Inspection new, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                                                                                            11987
[\nYes\n, \nEuro 6\n]                                                                            523
\nYes\n                                                                                          362
[\nYes\n, \n102 g CO2/km (comb)\n]                  

In [42]:
oto["Inspection new"].isnull().sum()/len(oto["Inspection new"])

0.7529995602738866

In [43]:
oto['Inspection new'].str[0].value_counts(dropna = False)

NaN        11987
\nYes\n     3570
\n           362
Name: Inspection new, dtype: int64

##### We chose the '\n' string in '.contains()'. So we cover both variables in the lists and out of the lists¶
'*' 1 → gives us 1 or 0 according to True/False

In [44]:
oto['Inspection new'].str[0].str.contains("\n", na = False)

0         True
1        False
2        False
3        False
4         True
         ...  
15914    False
15915    False
15916     True
15917    False
15918     True
Name: Inspection new, Length: 15919, dtype: bool

In [45]:
oto["Inspection_New_Bool"] = oto['Inspection new'].str[0].str.contains("\n", na = False)*1

In [46]:
oto["Inspection_New_Bool"].value_counts(dropna = False)

0    11987
1     3932
Name: Inspection_New_Bool, dtype: int64

##### 'Next Inspection'

In [47]:
# Examining Next Inspection new column
print('Checking Next Inspection new column')
print('--------------------------')
print(oto['Next Inspection'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Next Inspection'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Next Inspection'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Next Inspection'].dtype,'\n\n')

Checking Next Inspection new column
--------------------------
0         [\n06/2021\n, \n99 g CO2/km (comb)\n]
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN
                          ...                  
15914                                       NaN
15915    [\n01/2022\n, \n168 g CO2/km (comb)\n]
15916                                       NaN
15917                                       NaN
15918                                       NaN
Name: Next Inspection, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                                                                                              12384
\n04/2022\n                                                                                         62
\n03/2021\n                                                                                        

In [48]:
oto['Next Inspection'].isnull().sum()/len(oto['Next Inspection'])

0.7779383127080847

In [49]:
nxtins_list = ["".join(item).strip() if type(item) == list else item for item in oto['Next Inspection']]
oto['next_inspection'] = pd.DataFrame(nxtins_list)

In [50]:
oto.next_inspection.value_counts(dropna = False)

NaN                                                                          12384
\n04/2022\n                                                                     62
\n03/2021\n                                                                     38
\n03/2022\n                                                                     36
\n06/2021\n                                                                     34
                                                                             ...  
06/2020\n\n111 g CO2/km (comb)                                                   1
12/2018\n\n4 (Green)                                                             1
03/2021\n\n115 g CO2/km (comb)                                                   1
04/2020\n\n149 g CO2/km (comb)                                                   1
03/2020\n\n6.9 l/100 km (comb)\n8.2 l/100 km (city)\n6 l/100 km (country)        1
Name: next_inspection, Length: 1400, dtype: int64

In [51]:
oto["next_inspection"] = oto.next_inspection.str.extract("(\d\d/\d\d\d\d)")

In [52]:
oto.next_inspection.value_counts(dropna = False)

NaN        12384
06/2021      471
03/2021      210
05/2021      180
04/2021      171
           ...  
12/2022        1
02/2017        1
11/2022        1
01/1921        1
05/2016        1
Name: next_inspection, Length: 78, dtype: int64

In [53]:
oto.next_inspection = pd.to_datetime(oto.next_inspection, format = "%m/%Y")

In [54]:
oto.next_inspection.value_counts(dropna=False)

NaT           12384
2021-06-01      471
2021-03-01      210
2021-05-01      180
2021-04-01      171
              ...  
2016-04-01        1
1955-01-01        1
1999-01-01        1
2017-05-01        1
2016-05-01        1
Name: next_inspection, Length: 78, dtype: int64

##### 'Paint Type'

In [55]:
# Examining Paint Type new column
print('Checking Paint Type new column')
print('--------------------------')
print(oto['Paint Type'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Paint Type'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Paint Type'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Paint Type'].dtype,'\n\n')

Checking Paint Type new column
--------------------------
0        [\nMetallic\n]
1                   NaN
2        [\nMetallic\n]
3        [\nMetallic\n]
4        [\nMetallic\n]
              ...      
15914    [\nMetallic\n]
15915    [\nMetallic\n]
15916               NaN
15917               NaN
15918    [\nMetallic\n]
Name: Paint Type, Length: 15919, dtype: object 


Number of each values
--------------------------
[\nMetallic\n]       9794
NaN                  5772
[\nUni/basic\n]       347
[\nPerl effect\n]       6
Name: Paint Type, dtype: int64 


Number of missing values
--------------------------
5772 


Data type
--------------------------
object 




In [56]:
oto["Paint Type"].str[0]

0        \nMetallic\n
1                 NaN
2        \nMetallic\n
3        \nMetallic\n
4        \nMetallic\n
             ...     
15914    \nMetallic\n
15915    \nMetallic\n
15916             NaN
15917             NaN
15918    \nMetallic\n
Name: Paint Type, Length: 15919, dtype: object

In [57]:
oto["Paint Type"].str[0].str.strip("\n").value_counts(dropna = False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: Paint Type, dtype: int64

###### We should decide or specify its importance or value level for price prediction

In [58]:
oto['paint_type'] = oto['Paint Type'].str[0].str.strip('\n')

In [59]:
oto['paint_type'].value_counts(dropna = False)

Metallic       9794
NaN            5772
Uni/basic       347
Perl effect       6
Name: paint_type, dtype: int64

##### 'Country Version'

In [61]:
# Examining Country Version new column
print('Checking Country version new column')
print('--------------------------')
print(oto['Country version'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Country version'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Country version'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Country version'].dtype,'\n\n')

Checking Country version new column
--------------------------
0                  NaN
1                  NaN
2                  NaN
3                  NaN
4        [\nGermany\n]
             ...      
15914              NaN
15915    [\nGermany\n]
15916    [\nAustria\n]
15917              NaN
15918    [\nGermany\n]
Name: Country version, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                     8333
[\nGermany\n]           4502
[\nItaly\n]             1038
[\nEuropean Union\n]     507
[\nNetherlands\n]        464
[\nSpain\n]              325
[\nBelgium\n]            314
[\nAustria\n]            208
[\nCzech Republic\n]      52
[\nPoland\n]              49
[\nFrance\n]              38
[\nDenmark\n]             33
[\nHungary\n]             28
[\nJapan\n]                8
[\nSlovakia\n]             4
[\nCroatia\n]              4
[\nSweden\n]               3
[\nRomania\n]              2
[\nBulgaria\n]             2
[\nSerbia\n]               1


In [62]:
oto['Country version'].str[0].str.strip('\n').value_counts(dropna=False)

NaN               8333
Germany           4502
Italy             1038
European Union     507
Netherlands        464
Spain              325
Belgium            314
Austria            208
Czech Republic      52
Poland              49
France              38
Denmark             33
Hungary             28
Japan                8
Croatia              4
Slovakia             4
Sweden               3
Romania              2
Bulgaria             2
Egypt                1
Switzerland          1
Serbia               1
Luxembourg           1
Slovenia             1
Name: Country version, dtype: int64

In [63]:
## It's not essential for the result (price) but we can keep it.
## May be we can fillna using weight-mean in terms of values respectively

oto['country'] = oto['Country version'].str[0].str.strip('\n')

##### 'Cylinders'

In [64]:
# Examining Cylinders new column
print('Checking Cylinders new column')
print('--------------------------')
print(oto['Cylinders'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Cylinders'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Cylinders'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Cylinders'].dtype,'\n\n')

Checking Cylinders new column
--------------------------
0        [\n3\n]
1        [\n4\n]
2            NaN
3        [\n3\n]
4        [\n3\n]
          ...   
15914    [\n4\n]
15915    [\n4\n]
15916    [\n4\n]
15917    [\n4\n]
15918    [\n4\n]
Name: Cylinders, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n4\n]    8105
NaN        5680
[\n3\n]    2104
[\n5\n]      22
[\n6\n]       3
[\n2\n]       2
[\n8\n]       2
[\n1\n]       1
Name: Cylinders, dtype: int64 


Number of missing values
--------------------------
5680 


Data type
--------------------------
object 




In [65]:
oto['Cylinders'].str[0].str.strip('\n').value_counts(dropna=False)

4      8105
NaN    5680
3      2104
5        22
6         3
2         2
8         2
1         1
Name: Cylinders, dtype: int64

In [66]:
## we can handle with the missing values later. let's keep it for now
oto['Cylinders'] = oto['Cylinders'].str[0].str.strip('\n')

##### 'Emission Label'

In [68]:
# Examining Emission Label new column
print('Checking Emission Label new column')
print('--------------------------')
print(oto['Emission Label'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Emission Label'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Emission Label'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Emission Label'].dtype,'\n\n')

Checking Emission Label new column
--------------------------
0                    NaN
1        [\n4 (Green)\n]
2        [\n4 (Green)\n]
3                    NaN
4                    NaN
              ...       
15914                NaN
15915                NaN
15916                NaN
15917                NaN
15918    [\n4 (Green)\n]
Name: Emission Label, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                     11934
[\n4 (Green)\n]          3553
[\n1 (No sticker)\n]      381
[[], [], []]               40
[\n5 (Blue)\n]              8
[\n3 (Yellow)\n]            2
[\n2 (Red)\n]               1
Name: Emission Label, dtype: int64 


Number of missing values
--------------------------
11934 


Data type
--------------------------
object 




In [69]:
oto['Emission Label'].str[0].str.strip('\n').value_counts(dropna=False)

NaN               11974
4 (Green)          3553
1 (No sticker)      381
5 (Blue)              8
3 (Yellow)            2
2 (Red)               1
Name: Emission Label, dtype: int64

In [70]:
oto['emission_label'] = oto['Emission Label'].str[0].str.strip('\n')

In [71]:
oto.emission_label.value_counts(dropna = False)

NaN               11974
4 (Green)          3553
1 (No sticker)      381
5 (Blue)              8
3 (Yellow)            2
2 (Red)               1
Name: emission_label, dtype: int64

##### 'Full Service'

In [72]:
# Examining Full Service new column
print('Checking Full Service new column')
print('--------------------------')
print(oto['Full Service'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Full Service'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Full Service'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Full Service'].dtype,'\n\n')

Checking Full Service new column
--------------------------
0                                [\n, \n]
1                                     NaN
2                                     NaN
3        [\n, \n, \n99 g CO2/km (comb)\n]
4                 [\n, \n, \n4 (Green)\n]
                       ...               
15914                                 NaN
15915                                 NaN
15916                            [\n, \n]
15917                                 NaN
15918                                 NaN
Name: Full Service, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                                                                                           7704
[\n, \n, \n4 (Green)\n]                                                                       2235
[\n, \n, \nEuro 6\n]                                                                          2097
[\n, \n]                                                                        

In [73]:
list(oto['Full Service'].value_counts(dropna=False).index)

[nan,
 ['\n', '\n', '\n4 (Green)\n'],
 ['\n', '\n', '\nEuro 6\n'],
 ['\n', '\n'],
 ['\n', '\n', '\nEuro 6d-TEMP\n'],
 '\n',
 ['\n', '\n', '\n120 g CO2/km (comb)\n'],
 ['\n', '\n', '\n126 g CO2/km (comb)\n'],
 ['\n', '\n', '\n104 g CO2/km (comb)\n'],
 ['\n', '\n', '\n97 g CO2/km (comb)\n'],
 ['\n', '\n', '\n124 g CO2/km (comb)\n'],
 ['\n', '\n', '\n99 g CO2/km (comb)\n'],
 ['\n', '\n', '\n128 g CO2/km (comb)\n'],
 ['\n', '\n', '\n119 g CO2/km (comb)\n'],
 ['\n', '\n', '\n140 g CO2/km (comb)\n'],
 ['\n', '\n', '\n106 g CO2/km (comb)\n'],
 ['\n', '\n', '\n92 g CO2/km (comb)\n'],
 ['\n', '\n', '\n107 g CO2/km (comb)\n'],
 ['\n', '\n', '\n114 g CO2/km (comb)\n'],
 ['\n', '\n', '\n1 (No sticker)\n'],
 ['\n', '\n', '\n102 g CO2/km (comb)\n'],
 ['\n', '\n', '\n103 g CO2/km (comb)\n'],
 ['\n', '\n', '\nEuro 6c\n'],
 ['\n', '\n', '\n117 g CO2/km (comb)\n'],
 ['\n', '\n', '\n139 g CO2/km (comb)\n'],
 ['\n', '\n', '\n127 g CO2/km (comb)\n'],
 ['\n', '\n', '\n141 g CO2/km (comb)\n'],
 ['\n', '\n', 

In [74]:
oto.drop("Full Service", axis = 1, inplace = True)

##### 'Comfort & Convenience'

In [76]:
# Examining Comfort & Convenience new column
print('Checking \nComfort & Convenience\n new column')
print('--------------------------')
print(oto['\nComfort & Convenience\n'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['\nComfort & Convenience\n'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['\nComfort & Convenience\n'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['\nComfort & Convenience\n'].dtype,'\n\n')

Checking 
Comfort & Convenience
 new column
--------------------------
0                                                                                                                                                                                               [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]
1                                                                                                                                                                                                                                                                                                                                   [Air conditioning, Automatic climate control, Hill Holder, Leather steering wheel, Lumbar suppor

In [77]:
oto['\nComfort & Convenience\n'].value_counts(dropna = False).head(50)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    920
[Air conditioning, Electrical side mirrors, Hill Holder, Power windows]                                                                                                                                                                                                                                                                                                                                                                                                                                      

In [78]:
oto['\nComfort & Convenience\n'].value_counts(dropna = False).tail(50)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[Air conditioning, Automatic climate control, Cruise control, Electrically adjustable seats, Electrical side mirrors, Heated steering wheel, Hill Holder, Leather steering wheel, Lumbar support, Multi-function steering wheel, Navigation system, Power windows, Rain sensor, Seat heating, Seat ventilation]                                                                                                                                        1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Leather steering wheel, Multi-function steering wheel, Park Distance Control, Parking assist system sensors front, Parking assist system sensors rear, Split rear seats, Start-stop system]                                                                                                                                                            1
[Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Electric tailgate, Hea

In [ ]:
## may be this column contains the most important data for prediction of the price

## because there are some variables that have list in list, so we have to see all 'combined' values the variables have.

## we have to examine the unique values. we produce two function to do that. first we convert nan values to empty
## list than combine all values using set().update() syntax.

In [ ]:
# We can't operate with NaNs. We have to examine the unique values of this column.

#uni = set()
#uni.update(np.nan)
#uni.update(["a", "b", "a"])
#list(uni)

In [ ]:
# The new version of this data is a string. We have to convert its elments backto the list type.
# In order to use .get_dummies() method, we have to do that.

#oto['Comfort&Convenience'][0]

In [79]:
def unique_values(data, column_name):
    unique_vals = set()
    for rows in data[column_name]:
        unique_vals.update(rows)
    return list(unique_vals)

In [80]:
nans = oto['\nComfort & Convenience\n'].isnull()

In [81]:
oto.loc[nans, '\nComfort & Convenience\n']

9        NaN
30       NaN
53       NaN
168      NaN
191      NaN
        ... 
15791    NaN
15804    NaN
15805    NaN
15854    NaN
15864    NaN
Name: \nComfort & Convenience\n, Length: 920, dtype: object

In [82]:
def Nan_to_list(data, column_name):
    NaN_rows = data[column_name].isnull()
    data.loc[NaN_rows, column_name] = data.loc[NaN_rows, column_name].apply(lambda x : [])

In [83]:
Nan_to_list(oto, '\nComfort & Convenience\n')
unique_values(oto, '\nComfort & Convenience\n')

['Electrically adjustable seats',
 'Seat heating',
 'Light sensor',
 'Multi-function steering wheel',
 'Automatic climate control',
 'Windshield',
 'Air suspension',
 'Parking assist system self-steering',
 'Armrest',
 'Massage seats',
 'Lumbar support',
 'Parking assist system sensors front',
 'Heated steering wheel',
 'Tinted windows',
 'Park Distance Control',
 'Keyless central door lock',
 'Cruise control',
 'Parking assist system sensors rear',
 'Electrically heated windshield',
 'Electric Starter',
 'Rain sensor',
 'Panorama roof',
 'Hill Holder',
 'Parking assist system camera',
 'Split rear seats',
 'Seat ventilation',
 'Start-stop system',
 'Heads-up display',
 'Leather seats',
 'Sunroof',
 'Power windows',
 'Wind deflector',
 'Leather steering wheel',
 'Electrical side mirrors',
 'Auxiliary heating',
 'Electric tailgate',
 'Air conditioning',
 'Navigation system']

In [84]:
nxtins_list = [",".join(item).strip() if type(item) == list else item for item in oto['\nComfort & Convenience\n']]

In [85]:
oto["Comfort&Convenience"] = pd.DataFrame(nxtins_list)

In [86]:
oto['Comfort&Convenience'].value_counts(dropna=False)

                                                                                                                                                                                                                                                                                                                                                                                              920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                            216
Air conditioning,Electrical side mirrors,Power windows                                                                                                                                                                              

In [87]:
oto[oto['Comfort&Convenience'] == ""]

url      make_model                                  short_description body_type  price             vat          km registration      hp                  Type Previous Owners Next Inspection Inspection new       Warranty null         Make             Model    Offer Number First Registration       Body Color      Paint Type                   Body Color Original Upholstery Nr. of Doors Nr. of Seats Model Code         Gearing Type    Displacement Cylinders  Drive chain                Fuel                                                               Consumption               CO2 Emission Emission Class \nComfort & Convenience\n \nEntertainment & Media\n      \nExtras\n \nSafety & Security\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description Emission Label    Gears Country version Previous_Owner1 Previous_Owner  Inspection_New_Bool next_inspection paint_type country emission_label Comfort&Convenience
9                  https://www.autoscout24.com//offers/audi-a1-sportback-tfsi-ultra-95-s-tronic-amb-gasoline-white-e2c49a42-6aaa-4039-9af1-7546a20c110e         Audi A1              SPORTBACK TFSI ULTRA 95 S-TRONIC AMB.    Sedans  17990            None   16,103 km      06/2017   70 kW  [, Used, , Gasoline]             NaN             NaN            NaN   \n3 months\n   []     \nAudi\n      [\n, A1, \n]             NaN     [\n, 2017, \n]  [\n, White, \n]             NaN                           [\nBlanc\n]        NaN      [\n5\n]      [\n4\n]        NaN  [\n, Automatic, \n]    [\n999 cc\n]       NaN          NaN  [\n, Gasoline, \n]                                                                       NaN                        NaN            NaN                        []                       NaN             NaN                   NaN  [\nClim automatique,Ecran multifonction couleur,Capteur de pluie,Capteur de luminosité,Contrôle élect. de la pression des pneus,Régulateur de vitesse,EBD,ESP,8 Haut parleurs,ABS,Airbag conducteur,Airbag passager,Airbags latéraux avant,Airbags rideaux AV et AR,Antidémarrage électronique,Antipatinage,Appui-tête conducteur réglable hauteur,Appui-tête passager réglable en hauteur,Arrêt et redémarrage auto. du moteur,Bacs de portes avant,Banquette 1/3-2/3,Banquette AR rabattable,Boite à gant ferm...            NaN  [\n7\n]             NaN             NaN              1                    0             NaT        NaN     NaN            NaN                    
30                            https://www.autoscout24.com//offers/audi-a1-sportback-1-4tdi-attraction-diesel-black-be5e7705-5e6e-4ca0-a7df-fc6153d6e384         Audi A1                        Sportback 1.4TDI Attraction   Compact  11290            None   38,400 km      06/2016   66 kW    [, Used, , Diesel]             NaN             NaN            NaN  \n12 months\n   []     \nAudi\n      [\n, A1, \n]   [\n2780690\n]     [\n, 2016, \n]  [\n, Black, \n]             NaN                           [\nNegro\n]        NaN      [\n5\n]      [\n5\n]        NaN     [\n, Manual, \n]  [\n1,422 cc\n]         3  [\nfront\n]    [\n, Diesel, \n]        [[3 l/100 km (comb)], [3 l/100 km (city)], [3 l/100 km (country)]]                        NaN            NaN                        []                       NaN             NaN                   NaN  [\nVEHÍCULO NACIONAL, PROCEDE DE CONCESIONARIO OFICIAL , KMTS CERTIFICADOS CON LIBRO DE REVISIONES EN CONCESIONARIO OFICIAL, MUY BUEN ESTADO GENERAL Y MECANICO (21% IVA INCLUIDO EN EL PRECIO), AUX, SROP&GO, 5 PLAZAS, CIERRE CENTRALIZADO , ESPEJOS AUT..., ACEPTAMOS VEHICULO COMO PAGO , 

In [88]:
oto['Comfort&Convenience'].isnull().sum()

0

In [89]:
[np.nan if oto['Comfort&Convenience'].iloc[i] == "" else oto['Comfort&Convenience'].iloc[i] for i in range(len(oto['Comfort&Convenience']))]

['Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system',
 'Air conditioning,Automatic climate control,Hill Holder,Leather steering wheel,Lumbar support,Parking assist system sensors rear,Power windows,Start-stop system,Tinted windows',
 'Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Seat heating,Start-stop system',
 'Air suspension,Armrest,Auxiliary heating,Electrical side mirrors,Heads-up display,Hill Holder,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Power windows,Rain sensor,Seat heating,Sp

In [90]:
oto["Comfort&Convenience"] = [np.nan if oto['Comfort&Convenience'].iloc[i] == "" else oto['Comfort&Convenience'].iloc[i] for i in range(len(oto['Comfort&Convenience']))]

In [91]:
oto["Comfort&Convenience"].value_counts(dropna = False)

NaN                                                                                                                                                                                                                                                                                                                                                                                           920
Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                            216
Air conditioning,Electrical side mirrors,Power windows                                                                                                                                                                              

In [92]:
fill_most(oto, "make_model", "Comfort&Convenience")

In [93]:
oto['Comfort&Convenience'].isnull().sum()

0

In [94]:
oto['Comfort&Convenience'].value_counts()

Air conditioning,Electrical side mirrors,Hill Holder,Power windows                                                                                                                                                                                                                                                                                                                                                                                                                             389
Air conditioning,Armrest,Automatic climate control,Cruise control,Electrically adjustable seats,Electrical side mirrors,Electric tailgate,Heated steering wheel,Hill Holder,Keyless central door lock,Leather steering wheel,Light sensor,Lumbar support,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system camera,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system    259
Air conditioning,Cruise control,El

In [95]:
"Windshield" in oto["Comfort&Convenience"][0]

False

In [96]:
oto["Comfort&Convenience"].head()

0    Air conditioning,Armrest,Automatic climate control,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Light sensor,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors rear,Power windows,Rain sensor,Seat heating,Start-stop system
1                                                                                                                                 Air conditioning,Automatic climate control,Hill Holder,Leather steering wheel,Lumbar support,Parking assist system sensors rear,Power windows,Start-stop system,Tinted windows
2                           Air conditioning,Cruise control,Electrical side mirrors,Hill Holder,Leather steering wheel,Multi-function steering wheel,Navigation system,Park Distance Control,Parking assist system sensors front,Parking assist system sensors rear,Power windows,Seat heating,Start-stop system
3                                     Air suspension,Armrest,Auxiliary heating,Electr

In [97]:
oto["Comfort&Convenience"].str.get_dummies(sep = ",")

Air conditioning  Air suspension  Armrest  Automatic climate control  Auxiliary heating  Cruise control  Electric Starter  Electric tailgate  Electrical side mirrors  Electrically adjustable seats  Electrically heated windshield  Heads-up display  Heated steering wheel  Hill Holder  Keyless central door lock  Leather seats  Leather steering wheel  Light sensor  Lumbar support  Massage seats  Multi-function steering wheel  Navigation system  Panorama roof  Park Distance Control  Parking assist system camera  Parking assist system self-steering  Parking assist system sensors front  Parking assist system sensors rear  Power windows  Rain sensor  Seat heating  Seat ventilation  Split rear seats  Start-stop system  Sunroof  Tinted windows  Wind deflector  Windshield
0                     1               0        1                          1                  0               1                 0                  0                        1                              0                               0                 0                      0            1                          0              0                       1             1               0              0                              1                  1              0                      1                             0                                    0                                    0                                   1              1            1             1                 0                 0                  1        0               0               0           0
1                     1               0        0                          1                  0               0                 0                  0                        0                              0                               0                 0                      0            1                          0              0                       1             0               1              0                              0                  0              0                      0                             0                                    0                                    0                                   1              1            0             0                 0                 0                  1        0               1               0           0
2                     1               0        0                          0                  0               1                 0                  0                        1                              0                               0                 0                      0            1                          0              0                       1             0               0              0                              1                  1              0                      1                             0                                    0                                    1                                   1              1            0             1                 0                 0                  1        0               0               0           0
3                     0               1        1                          0                  1               0                 0                  0                        1                              0                               0                 1                      0            1                          0              0                       1             1               1              0                              1                  1              0                      0                             0                                    0                                    0                                   0              1            1             1                 0                 1                  1        0               0               0           0
4                     1               0        1                          1                  0               0  

In [98]:
oto = oto.join(oto["Comfort&Convenience"].str.get_dummies(sep = ",").add_prefix("cc_"))

In [99]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

In [100]:
oto.shape

(15919, 88)

##### '\nEntertainment & Media\n'

In [101]:
# Examining \nEntertainment & Media\n new column
print('Checking \nEntertainment & Media\n new column')
print('--------------------------')
print(oto['\nEntertainment & Media\n'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['\nEntertainment & Media\n'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['\nEntertainment & Media\n'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['\nEntertainment & Media\n'].dtype,'\n\n')

Checking 
Entertainment & Media
 new column
--------------------------
0                                           [Bluetooth, Hands-free equipment, On-board computer, Radio]
1                             [Bluetooth, Hands-free equipment, On-board computer, Radio, Sound system]
2                                                                              [MP3, On-board computer]
3        [Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, Sound system, USB]
4                      [Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]
                                                      ...                                              
15914                   [Bluetooth, Digital radio, Hands-free equipment, On-board computer, Radio, USB]
15915                                      [Bluetooth, Digital radio, Hands-free equipment, Radio, USB]
15916                                       [Bluetooth, Hands-free equipment, On-board computer, 

In [102]:
oto['\nEntertainment & Media\n'][0]

['Bluetooth', 'Hands-free equipment', 'On-board computer', 'Radio']

In [103]:
",".join(oto['\nEntertainment & Media\n'][0])

'Bluetooth,Hands-free equipment,On-board computer,Radio'

In [104]:
Nan_to_list(oto, '\nEntertainment & Media\n')
unique_values(oto, '\nEntertainment & Media\n')

['MP3',
 'Television',
 'Bluetooth',
 'CD player',
 'On-board computer',
 'Hands-free equipment',
 'Radio',
 'Sound system',
 'Digital radio',
 'USB']

In [105]:
oto['\nEntertainment & Media\n'].value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[]                                                                                                           1374
[Bluetooth, Hands-free equipment, On-board computer, Radio, USB]                                             1282
[Bluetooth, Hands-free equipment, MP3, On-board computer, Radio, USB]                                         982
[Bluetooth, CD player, Hands-free equipment, MP3, On-board computer, Radio, USB]                              783
[On-board computer, Radio]                                                                                    487
                                                                                                             ... 
[CD player, Digital radio, Hands-free equipment, On-board computer, Radio, Sound system, Television, USB]       1
[Digital radio, MP3, On-board computer, Radio, Sound system, USB]                                               1
[Digital radio, Hands-free equipment, MP3, On-board computer, USB]                      

In [106]:
nxtins_list = [",".join(item).strip() if type(item) == list else item for item in oto['\nEntertainment & Media\n']]

In [107]:
nxtins_list

['Bluetooth,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system',
 'MP3,On-board computer',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'CD player,MP3,Radio',
 'Radio',
 '',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,Hands-free equipment,On-board computer,Radio,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,MP3,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-

In [108]:
oto['Entertainment&Media'] = pd.DataFrame(nxtins_list)

In [109]:
oto['Entertainment&Media'].value_counts(dropna=False)

                                                                            1374
Bluetooth,Hands-free equipment,On-board computer,Radio,USB                  1282
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB               982
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB     783
On-board computer,Radio                                                      487
                                                                            ... 
Bluetooth,CD player,Digital radio,MP3,Radio,USB                                1
Hands-free equipment,On-board computer,Sound system                            1
Bluetooth,Digital radio,On-board computer,Sound system,USB                     1
Bluetooth,Digital radio,MP3,On-board computer,Radio,Sound system               1
Hands-free equipment,MP3,On-board computer,Sound system,USB                    1
Name: Entertainment&Media, Length: 347, dtype: int64

In [110]:
oto['Entertainment&Media'].isnull().sum()

0

In [111]:
[np.nan if oto['Entertainment&Media'].iloc[i] == "" else oto['Entertainment&Media'].iloc[i] for i in range(len(oto['Entertainment&Media']))]

['Bluetooth,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system',
 'MP3,On-board computer',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio,Sound system,USB',
 'CD player,MP3,Radio',
 'Radio',
 nan,
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,Hands-free equipment,On-board computer,Radio,USB',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'Bluetooth,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,On-board computer,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB',
 'CD player,MP3,Radio',
 'Bluetooth,CD player,Hands-free equipment,MP3,On

In [112]:
oto['Entertainment&Media'] = [np.nan if oto['Entertainment&Media'].iloc[i] == "" else oto['Entertainment&Media'].iloc[i] for i in range(len(oto['Entertainment&Media']))]

In [113]:
fill_most(oto, "make_model", "Entertainment&Media")

In [114]:
oto['Entertainment&Media'].value_counts(dropna = False)

Bluetooth,Hands-free equipment,On-board computer,Radio,USB                  2015
Bluetooth,Hands-free equipment,MP3,On-board computer,Radio,USB              1206
Bluetooth,CD player,Hands-free equipment,MP3,On-board computer,Radio,USB    1049
Bluetooth,Hands-free equipment,On-board computer,Radio                       529
On-board computer,Radio                                                      487
                                                                            ... 
Hands-free equipment,On-board computer,Sound system                            1
Bluetooth,Digital radio,MP3,On-board computer,Radio,Sound system               1
Bluetooth,Digital radio,On-board computer,Sound system,USB                     1
CD player,Digital radio,Hands-free equipment,Radio,USB                         1
Hands-free equipment,MP3,On-board computer,Sound system,USB                    1
Name: Entertainment&Media, Length: 346, dtype: int64

In [115]:
oto['Entertainment&Media'].str.get_dummies(sep = ",")

Bluetooth  CD player  Digital radio  Hands-free equipment  MP3  On-board computer  Radio  Sound system  Television  USB
0              1          0              0                     1    0                  1      1             0           0    0
1              1          0              0                     1    0                  1      1             1           0    0
2              0          0              0                     0    1                  1      0             0           0    0
3              1          1              0                     1    1                  1      1             1           0    1
4              1          1              0                     1    1                  1      1             0           0    1
...          ...        ...            ...                   ...  ...                ...    ...           ...         ...  ...
15914          1          0              1                     1    0                  1      1             0           0    1
15915          1          0              1                     1    0                  0      1             0           0    1
15916          1          0              0                     1    0                  1      1             0           0    0
15917          1          0              1                     0    0                  0      1             0           0    1
15918          0          0              0                     0    0                  0      0             0           0    1

[15919 rows x 10 columns]

In [116]:
oto = oto.join(oto['Entertainment&Media'].str.get_dummies(sep = ",").add_prefix("em_"))

In [117]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

##### '\nExtras\n'

In [118]:
# Examining \nExtras\n new column
print('Checking \nExtras\n new column')
print('--------------------------')
print(oto['\nExtras\n'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['\nExtras\n'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['\nExtras\n'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['\nExtras\n'].dtype,'\n\n')

Checking 
Extras
 new column
--------------------------
0                    [Alloy wheels, Catalytic Converter, Voice Control]
1          [Alloy wheels, Sport seats, Sport suspension, Voice Control]
2                                         [Alloy wheels, Voice Control]
3                            [Alloy wheels, Sport seats, Voice Control]
4        [Alloy wheels, Sport package, Sport suspension, Voice Control]
                                      ...                              
15914                                      [Alloy wheels, Touch screen]
15915                       [Alloy wheels, Touch screen, Voice Control]
15916                                                    [Alloy wheels]
15917                                      [Alloy wheels, Touch screen]
15918                                      [Alloy wheels, Touch screen]
Name: \nExtras\n, Length: 15919, dtype: object 


Number of each values
--------------------------
[Alloy wheels]                                       

In [119]:
[",".join(item).strip() if type(item) == list else item for item in oto['\nExtras\n']]

['Alloy wheels,Catalytic Converter,Voice Control',
 'Alloy wheels,Sport seats,Sport suspension,Voice Control',
 'Alloy wheels,Voice Control',
 'Alloy wheels,Sport seats,Voice Control',
 'Alloy wheels,Sport package,Sport suspension,Voice Control',
 'Alloy wheels,Sport package,Sport seats,Sport suspension',
 'Alloy wheels,Sport package,Sport seats,Sport suspension',
 'Alloy wheels',
 'Alloy wheels',
 nan,
 'Alloy wheels,Shift paddles',
 'Alloy wheels,Sport seats',
 'Alloy wheels,Catalytic Converter,Sport package,Sport seats,Sport suspension,Voice Control',
 'Alloy wheels,Sport seats,Sport suspension',
 'Alloy wheels,Sport seats,Sport suspension',
 'Alloy wheels',
 'Alloy wheels,Sport package,Sport seats',
 'Alloy wheels,Sport package',
 'Alloy wheels',
 'Alloy wheels,Catalytic Converter,Shift paddles,Voice Control',
 'Alloy wheels,Shift paddles,Sport package,Voice Control',
 'Alloy wheels,Sport seats,Voice Control',
 'Alloy wheels,Catalytic Converter,Sport seats,Voice Control,Winter tyre

In [120]:
temp = pd.DataFrame([",".join(item).strip() if type(item) == list else item for item in oto['\nExtras\n']])

In [121]:
temp.isnull().sum()

0    2962
dtype: int64

In [122]:
oto["extra"] = pd.DataFrame([",".join(item).strip() if type(item) == list else item for item in oto['\nExtras\n']])

In [123]:
oto.extra.value_counts(dropna = False)

Alloy wheels                                                                                                      3245
NaN                                                                                                               2962
Alloy wheels,Touch screen                                                                                          697
Alloy wheels,Voice Control                                                                                         577
Alloy wheels,Touch screen,Voice Control                                                                            541
                                                                                                                  ... 
Alloy wheels,Sport suspension,Touch screen,Tuned car                                                                 1
Alloy wheels,Cab or rented Car,Catalytic Converter,Sport package,Sport seats                                         1
Alloy wheels,Cab or rented Car,Roof rack,Sport p

In [124]:
fill_most(oto, "make_model", "extra")

In [125]:
oto.extra.value_counts(dropna = False)

Alloy wheels                                                                                                        6174
Alloy wheels,Touch screen                                                                                            697
Alloy wheels,Voice Control                                                                                           577
Alloy wheels,Touch screen,Voice Control                                                                              541
Alloy wheels,Roof rack                                                                                               385
                                                                                                                    ... 
Alloy wheels,Roof rack,Shift paddles,Ski bag,Sport package,Sport seats,Sport suspension                                1
Alloy wheels,Sport suspension,Touch screen,Tuned car                                                                   1
Alloy wheels,Cab or rented Car,C

In [126]:
oto = oto.join(oto["extra"].str.get_dummies(sep = ",").add_prefix("ex_"))

In [127]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

In [128]:
oto.shape

(15919, 117)

##### '\nSafety & Security\n'

In [129]:
# Examining \nSafety & Security\n new column
print('Checking \nSafety & Security\n new column')
print('--------------------------')
print(oto['\nSafety & Security\n'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['\nSafety & Security\n'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['\nSafety & Security\n'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['\nSafety & Security\n'].dtype,'\n\n')

Checking 
Safety & Security
 new column
--------------------------
0                                                                                                                                                       [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]
1                                                                                                               [ABS, Central door lock, Central door lock with remote control, Daytime running lights, Driver-side airbag, Electronic stability control, Head airbag, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]
2                                                                                                                          

In [130]:
temp1 = [",".join(item).strip() if type(item) == list else item for item in oto['\nSafety & Security\n']]

In [131]:
oto["Safe&Secure"] = pd.DataFrame(temp1)

In [132]:
oto["Safe&Secure"].value_counts(dropna = False)

NaN                                                                                                                                                                                                                                                                                                                                                            982
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                   538
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                 

In [133]:
fill_most(oto, "make_model", "Safe&Secure")

In [134]:
oto["Safe&Secure"].value_counts(dropna = False)

ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                   825
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Immobilizer,Isofix,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                                                                                                                              480
ABS,Central door lock,Daytime running lights,Driver-side airbag,Electronic stability control,Fog lights,Immobilizer,Isofix,LED Daytime Running Lights,Passenger-side airbag,Power steering,Side airbag,Tire pressure monitoring system,Traction control                                           

In [135]:
oto = oto.join(oto["Safe&Secure"].str.get_dummies(sep = ",").add_prefix("ss_"))

In [136]:
oto.head()

url make_model                                   short_description body_type  price               vat         km registration      hp                                     Type Previous Owners                        Next Inspection                      Inspection new                          Warranty null      Make         Model     Offer Number First Registration       Body Color      Paint Type           Body Color Original          Upholstery Nr. of Doors Nr. of Seats      Model Code         Gearing Type    Displacement Cylinders  Drive chain                                   Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                                                                                                                                                                                                                                     \nComfort & Convenience\n                                                                       \nEntertainment & Media\n                                                      \nExtras\n                                                                                                                                                                                                                                                                                 \nSafety & Security\n  \
0         https://www.autoscout24.com//offers/audi-a1-sportback-1-4-tdi-s-tronic-xenon-navi-klima-diesel-black-bdab349a-caa5-41b0-98eb-c1345b84445e    Audi A1         Sportback 1.4 TDI S-tronic Xenon Navi Klima    Sedans  15770    VAT deductible  56,013 km      01/2016   66 kW  [, Used, , Diesel (Particulate Filter)]           \n2\n  [\n06/2021\n, \n99 g CO2/km (comb)\n]               [\nYes\n, \nEuro 6\n]           [\n, \n, \n4 (Green)\n]   []  \nAudi\n  [\n, A1, \n]  [\nLR-062483\n]     [\n, 2016, \n]  [\n, Black, \n]  [\nMetallic\n]           [\nMythosschwarz\n]  [\nCloth, Black\n]      [\n5\n]      [\n5\n]  [\n0588/BDF\n]  [\n, Automatic, \n]  [\n1,422 cc\n]         3  [\nfront\n]  [\n, Diesel (Particulate Filter), \n]  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]   [\n99 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Armrest, Automatic climate control, Cruise control, Electrical side mirrors, Hill Holder, Leather steering wheel, Light sensor, Multi-function steering wheel, Navigation system, Park Distance Control, Parking assist system sensors rear, Power windows, Rain sensor, Seat heating, Start-stop system]                                     [Bluetooth, Hands-free equipment, On-board computer, Radio]              [Alloy wheels, Catalytic Converter, Voice Control]                                          [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Fog lights, Immobilizer, Isofix, Passenger-side airbag, Power steering, Side airbag, Tire pressure monitoring system, Traction control, Xenon headlights]   
1                                      https://www.autoscout24.com//offers/audi-a1-1-8-tfsi-sport-gasoline-red-b2547f8a-e83f-6237-e053-e250040a56df    Audi A1                                      1.8 TFSI sport    Sedans  14500  Price negotiable  80,000 km      03/2017  141 kW                     [, Used, , Gasoline]             NaN                                    NaN                                 NaN                               NaN   []  \nAudi\n  [\n, A1, \n]              NaN     [\n, 2017, \n]    [\n, Red, \n]             NaN                           NaN   [\nCloth, Grey\n]      [\n3\n]      [\n4\n]  [\n0588/BCY\n]  [\n, Automatic, \n]  [\n1,798 cc\n]         4  [\nfront\n]                     [\n, Gasoline, \n]  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]  [\n129 g CO2/km (comb)\n]   [\nEuro 6\n]                                                

In [138]:
oto.shape

(15919, 147)

##### 'Consumption'

In [139]:
# Examining Consumption new column
print('Checking Consumption new column')
print('--------------------------')
print(oto['Consumption'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Consumption'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Consumption'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Consumption'].dtype,'\n\n')

Checking Consumption new column
--------------------------
0                  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]
1                  [[5.6 l/100 km (comb)], [7.1 l/100 km (city)], [4.7 l/100 km (country)]]
2                  [[3.8 l/100 km (comb)], [4.4 l/100 km (city)], [3.4 l/100 km (country)]]
3                  [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]
4                  [[4.1 l/100 km (comb)], [4.6 l/100 km (city)], [3.8 l/100 km (country)]]
                                                ...                                        
15914              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
15915    [\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]
15916              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
15917              [[5.3 l/100 km (comb)], [6.2 l/100 km (city)], [4.7 l/100 km (country)]]
15918              [[

In [140]:
oto['Consumption'].sample(55)

5014               [[5.1 l/100 km (comb)], [5.8 l/100 km (city)], [4.7 l/100 km (country)]]
3147                 [[4 l/100 km (comb)], [4.9 l/100 km (city)], [3.5 l/100 km (country)]]
2692               [[4.8 l/100 km (comb)], [5.5 l/100 km (city)], [4.4 l/100 km (country)]]
12815                                                                                   NaN
13874              [[5.9 l/100 km (comb)], [7.6 l/100 km (city)], [5.1 l/100 km (country)]]
13087                                                                                   NaN
14320                                                                                   NaN
12946              [[7.1 l/100 km (comb)], [8.8 l/100 km (city)], [5.8 l/100 km (country)]]
4877               [[4.1 l/100 km (comb)], [4.6 l/100 km (city)], [3.8 l/100 km (country)]]
14987              [[4.7 l/100 km (comb)], [5.1 l/100 km (city)], [4.4 l/100 km (country)]]
14165              [[3.3 l/100 km (comb)], [3.5 l/100 km (city)], [3.1 l/100 km 

In [141]:
oto['Consumption'].sample(55)

1149               [[4.5 l/100 km (comb)], [5.5 l/100 km (city)], [3.9 l/100 km (country)]]
3956               [[3.9 l/100 km (comb)], [4.4 l/100 km (city)], [3.6 l/100 km (country)]]
3518               [[3.8 l/100 km (comb)], [4.5 l/100 km (city)], [3.4 l/100 km (country)]]
1970               [[4.8 l/100 km (comb)], [5.8 l/100 km (city)], [4.2 l/100 km (country)]]
1921               [[4.9 l/100 km (comb)], [5.9 l/100 km (city)], [4.3 l/100 km (country)]]
13308                                                                                   NaN
11779              [[4.3 l/100 km (comb)], [5.1 l/100 km (city)], [3.9 l/100 km (country)]]
15639              [[6.8 l/100 km (comb)], [8.7 l/100 km (city)], [5.7 l/100 km (country)]]
13077              [[5.3 l/100 km (comb)], [6.8 l/100 km (city)], [4.5 l/100 km (country)]]
15372                                                                                   NaN
526                  [[4.2 l/100 km (comb)], [5 l/100 km (city)], [3.7 l/100 km 

In [142]:
oto['Consumption'].sample(55)

1624               [[4.9 l/100 km (comb)], [6.2 l/100 km (city)], [4.2 l/100 km (country)]]
7398                 [[3.5 l/100 km (comb)], [4 l/100 km (city)], [3.2 l/100 km (country)]]
11016              [[3.9 l/100 km (comb)], [4.6 l/100 km (city)], [3.6 l/100 km (country)]]
3408               [[3.9 l/100 km (comb)], [4.1 l/100 km (city)], [3.7 l/100 km (country)]]
3602              [[8.3 l/100 km (comb)], [11.3 l/100 km (city)], [6.6 l/100 km (country)]]
12345              [[5.9 l/100 km (comb)], [7.5 l/100 km (city)], [4.9 l/100 km (country)]]
12819                [[6.3 l/100 km (comb)], [8 l/100 km (city)], [5.3 l/100 km (country)]]
10755                                 [[4.7 l/100 km (comb)], [], [8.6 l/100 km (country)]]
7925               [[3.4 l/100 km (comb)], [3.9 l/100 km (city)], [3.1 l/100 km (country)]]
11605              [[4.3 l/100 km (comb)], [5.1 l/100 km (city)], [3.9 l/100 km (country)]]
9820               [[5.2 l/100 km (comb)], [6.6 l/100 km (city)], [4.3 l/100 km 

There are three tpyes of value which can effect the result.

-- Type 1-one list and three sub list (comb,city,country), like= [[3.8 l/100 km (comb)], [4.3 l/100 km (city)], [3.5 l/100 km (country)]]

-- Type 2-one list and no sub list (comb,city,country), like = [\n, 7.4 l/100 km (comb), \n, 9.2 l/100 km (city), \n, 6.3 l/100 km (country), \n]

--Type 3-one list and three sub lists some of which are empty, like = [[], [4.6 l/100 km (city)], [5.7 l/100 km (country)]] or [[4.2 l/100 km (comb)], [], []] or [[], [], [5.1 l/100 km (country)]]

So, we use str.extract() to select numeric consumption(comb) in different ways below.

In [143]:
oto.Consumption.str[0]

0        [3.8 l/100 km (comb)]
1        [5.6 l/100 km (comb)]
2        [3.8 l/100 km (comb)]
3        [3.8 l/100 km (comb)]
4        [4.1 l/100 km (comb)]
                 ...          
15914    [5.3 l/100 km (comb)]
15915                       \n
15916    [5.3 l/100 km (comb)]
15917    [5.3 l/100 km (comb)]
15918    [6.8 l/100 km (comb)]
Name: Consumption, Length: 15919, dtype: object

In [144]:
oto.Consumption.str[0].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[13.8 l/100 km (comb)]      1
[5.3 kg/100 km (comb)]      1
[5.2 l/100 km (comb)]     429
[6.5 l/100 km (comb)]      36
[3.6 kg/100 km (comb)]      1
[8.1 l/100 km (comb)]       2
[54 l/100 km (comb)]        1
[5.8 l/100 km (comb)]     142
[]                        127
[5.4 kg/100 km (comb)]      1
[7.2 l/100 km (comb)]       6
[4.9 l/100 km (comb)]     348
[33 l/100 km (comb)]        1
[1.2 l/100 km (comb)]       1
[5.1 l/100 km (comb)]     627
[4.8 l/100 km (comb)]     523
[6.3 l/100 km (comb)]     141
[1 l/100 km (comb)]         1
[38 l/100 km (comb)]        2
\n                        850
[5.4 l/100 km (comb)]     662
[7.3 l/100 km (comb)]       2
[9.1 l/100 km (comb)]       1
[0 l/100 km (comb)]         2
[6.1 l/100 km (comb)]     135
[8.3 l/100 km (comb)]      19
[3.6 l/100 km (comb)]     193
[5.6 l/100 km (comb)]     568
[11 l/100 km (comb)]        1
[4.6 l/100 km (comb)]     420
[10 l/100 km (comb)]       34
[8.6 l/100 km (comb)]       3
[5.3 l/100 km (comb)]     374
[3 l/100 k

In [145]:
oto.Consumption.str[0].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[3.4 l/100 km (comb)]       94
[7.2 l/100 km (comb)]        6
[5.1 kg/100 km (comb)]       3
[6.5 l/100 km (comb)]       36
[5.4 l/100 km (comb)]      662
[33 l/100 km (comb)]         1
[8.3 l/100 km (comb)]       19
[43 l/100 km (comb)]         1
[11 l/100 km (comb)]         1
[3.6 kg/100 km (comb)]       1
[6 l/100 km (comb)]        278
[51 l/100 km (comb)]         4
[5 l/100 km (comb)]        513
[13.8 l/100 km (comb)]       1
[38 l/100 km (comb)]         2
[6.6 l/100 km (comb)]      119
[5.2 l/100 km (comb)]      429
[55 l/100 km (comb)]         1
[4.5 l/100 km (comb)]      511
[4.4 l/100 km (comb)]      595
[4.2 l/100 km (comb)]      408
[6.8 l/100 km (comb)]      134
[7.1 l/100 km (comb)]       38
[4.3 l/100 km (comb)]      295
[4.8 l/100 km (comb)]      523
[8.7 l/100 km (comb)]        3
[3.8 l/100 km (comb)]      585
[5.9 l/100 km (comb)]      308
[4 l/100 km (comb)]        712
[3.2 l/100 km (comb)]       25
[6.2 l/100 km (comb)]      184
[7.5 l/100 km (comb)]        1
[40 l/10

In [146]:
oto.Consumption.str[0].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[13.8 l/100 km (comb)]      1
[3.6 l/100 km (comb)]     193
[7 l/100 km (comb)]         9
[8.3 kg/100 km (comb)]      1
[6.5 l/100 km (comb)]      36
[6.6 l/100 km (comb)]     119
[8.1 l/100 km (comb)]       2
[7.5 l/100 km (comb)]       1
[7.6 l/100 km (comb)]      14
[6.3 l/100 km (comb)]     141
[6.8 l/100 km (comb)]     134
[51 l/100 km (comb)]        4
[3.9 l/100 km (comb)]     732
[7.9 l/100 km (comb)]       2
[46 l/100 km (comb)]        1
[]                        127
[3.6 kg/100 km (comb)]      1
[3.4 kg/100 km (comb)]     12
[5.8 l/100 km (comb)]     142
[8.6 l/100 km (comb)]       3
[7.3 l/100 km (comb)]       2
\n                        850
[1.2 l/100 km (comb)]       1
[3.5 kg/100 km (comb)]      3
[3.5 l/100 km (comb)]     285
[38 l/100 km (comb)]        2
[3.3 l/100 km (comb)]     298
[6.2 l/100 km (comb)]     184
[40 l/100 km (comb)]        2
[43 l/100 km (comb)]        1
[4.3 l/100 km (comb)]     295
[55 l/100 km (comb)]        1
[33 l/100 km (comb)]        1
[5.9 l/100

There are 850 values in which only 'one' list (the value of "\n" indicates that). Consists of no sub list.

There are 127 values is '[]' which means there is no comb consumption. Only have city or country or both.

There are still 1906 NaNs.

In [147]:
oto.Consumption.str[0].str[0].value_counts(dropna = False)

NaN                     2033
\n                       850
3.9 l/100 km (comb)      732
4 l/100 km (comb)        712
5.4 l/100 km (comb)      662
                        ... 
8.3 kg/100 km (comb)       1
1.2 l/100 km (comb)        1
3.6 kg/100 km (comb)       1
5.3 kg/100 km (comb)       1
5.4 kg/100 km (comb)       1
Name: Consumption, Length: 81, dtype: int64

In [148]:
oto["Consumption"][12625][0][0]

'\n'

In [149]:
oto.Consumption.str[0].str[0].unique()

array(['3.8 l/100 km (comb)', '5.6 l/100 km (comb)',
       '4.1 l/100 km (comb)', '3.5 l/100 km (comb)',
       '3.7 l/100 km (comb)', nan, '4 l/100 km (comb)',
       '4.9 l/100 km (comb)', '4.2 l/100 km (comb)',
       '4.5 l/100 km (comb)', '4.4 l/100 km (comb)',
       '4.3 l/100 km (comb)', '3 l/100 km (comb)', '3.6 l/100 km (comb)',
       '3.4 l/100 km (comb)', '\n', '3.9 l/100 km (comb)',
       '5.1 l/100 km (comb)', '5.2 l/100 km (comb)',
       '4.6 l/100 km (comb)', '4.8 l/100 km (comb)',
       '5.8 l/100 km (comb)', '4.7 l/100 km (comb)', '5 l/100 km (comb)',
       '43 l/100 km (comb)', '13.8 l/100 km (comb)', '6 l/100 km (comb)',
       '5.9 l/100 km (comb)', '51 l/100 km (comb)', '5.3 l/100 km (comb)',
       '5.3 kg/100 km (comb)', '5.5 l/100 km (comb)',
       '3.4 kg/100 km (comb)', '10 l/100 km (comb)',
       '3.3 kg/100 km (comb)', '3.2 l/100 km (comb)',
       '3.5 kg/100 km (comb)', '6.6 l/100 km (comb)',
       '3.3 l/100 km (comb)', '8.3 l/100 km (comb)',
  

In [150]:
oto.Consumption.str[0].str[0].str.extract("(\d.\d|\d)")[0].unique()

array(['3.8', '5.6', '4.1', '3.5', '3.7', nan, '4', '4.9', '4.2', '4.5',
       '4.4', '4.3', '3', '3.6', '3.4', '3.9', '5.1', '5.2', '4.6', '4.8',
       '5.8', '4.7', '5', '1', '6', '5.9', '5.3', '5.5', '3.3', '3.2',
       '6.6', '8.3', '6.5', '7.1', '8.1', '5.4', '6.4', '6.7', '6.2',
       '7.3', '6.3', '5.7', '6.1', '6.8', '7.5', '7.4', '0', '7.8', '3.1',
       '6.9', '7', '7.2', '8', '9.1', '8.6', '8.7', '7.9', '1.2', '7.6'],
      dtype=object)

In [151]:
oto.Consumption.str[0].str[0].str.extract("(^\d*.\d*)").iloc[:,0].unique()

array(['3.8', '5.6', '4.1', '3.5', '3.7', nan, '4 ', '4.9', '4.2', '4.5',
       '4.4', '4.3', '3 ', '3.6', '3.4', '3.9', '5.1', '5.2', '4.6',
       '4.8', '5.8', '4.7', '5 ', '43 ', '13.8', '6 ', '5.9', '51 ',
       '5.3', '5.5', '10 ', '3.3', '3.2', '6.6', '8.3', '6.5', '7.1',
       '8.1', '5.4', '40 ', '38 ', '6.4', '6.7', '6.2', '7.3', '6.3',
       '5.7', '6.1', '6.8', '7.5', '7.4', '0 ', '7.8', '3.1', '6.9', '7 ',
       '7.2', '8 ', '11 ', '9.1', '8.6', '8.7', '7.9', '55 ', '54 ',
       '1.2', '32 ', '33 ', '50 ', '1 ', '46 ', '7.6'], dtype=object)

If consumption is two digits, Extraction function takes only first one.
eg.: 40 → 4
eg.: 33 → 3

In [153]:
oto.Consumption.str[0].str[0].str.extract("(\d.\d|\d)").isnull().sum()*100/oto.Consumption.str[0].str[0].str.extract('(\d.\d|\d)').shape[0]

0    18.110434
dtype: float64

In [154]:
oto["consumption_comb"] = oto.Consumption.str[0].str[0].str.extract("(\d.\d|\d)")

In [155]:
oto.consumption_comb.value_counts(dropna = False)

NaN    2883
3.9     732
4       716
5.4     663
5.1     630
4.4     595
3.8     585
5.6     568
4.7     555
4.8     523
5       520
4.5     511
5.2     429
4.6     420
4.2     408
5.3     375
3.7     369
4.9     348
5.5     342
4.1     341
5.9     308
3.3     307
5.7     302
4.3     295
3.5     288
6       278
3.6     194
6.2     184
5.8     142
6.3     141
6.1     135
6.8     134
6.6     119
3.4     106
3        73
6.4      64
7.4      62
7.1      38
1        37
6.5      36
6.7      33
3.2      25
6.9      21
8.3      20
7.6      14
7         9
3.1       7
7.8       6
7.2       6
8         5
8.6       3
8.7       3
7.3       2
0         2
7.9       2
8.1       2
1.2       1
9.1       1
7.5       1
Name: consumption_comb, dtype: int64

Now, lets go into the other types. Let's try str[1]

In [156]:
oto.Consumption.str[1].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                       1906
[5 l/100 km (city)]        642
[5.8 l/100 km (city)]      597
[4.5 l/100 km (city)]      577
[]                         516
                          ... 
4.1 l/100 km (comb)          1
[19.9 l/100 km (city)]       1
[6.8 kg/100 km (city)]       1
[9 l/100 km (city)]          1
[4.4 kg/100 km (city)]       1
Name: Consumption, Length: 130, dtype: int64

In [157]:
oto.Consumption.str[1].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


4.8 l/100 km (comb)         23
[10.8 l/100 km (city)]       3
[5.7 l/100 km (city)]      365
7.9 l/100 km (comb)          1
[11 l/100 km (city)]         4
[5 l/100 km (city)]        642
[9 l/100 km (city)]          1
[10.2 l/100 km (city)]      21
[19.9 l/100 km (city)]       1
NaN                       1906
[7.5 l/100 km (city)]      217
[6.9 l/100 km (city)]      215
[62 l/100 km (city)]         4
[6.5 kg/100 km (city)]       1
[11.3 l/100 km (city)]      19
6.4 l/100 km (comb)         11
[8 l/100 km (city)]        101
4.1 l/100 km (comb)          1
[4.3 kg/100 km (city)]      21
[4.5 kg/100 km (city)]       3
[9.1 l/100 km (city)]       12
[64 l/100 km (city)]         1
[10.4 l/100 km (city)]       1
5.6 l/100 km (comb)         50
[6.5 l/100 km (city)]      161
[8.6 l/100 km (city)]       27
4.4 l/100 km (comb)         28
5.7 l/100 km (comb)         40
4 l/100 km (comb)            1
[3.5 l/100 km (city)]      230
[7.9 l/100 km (city)]       77
[8.8 l/100 km (city)]        2
[6.8 kg/

In [158]:
oto.Consumption.str[1].value_counts(dropna = False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


3.9 l/100 km (comb)           1
[10 l/100 km (city)]         16
NaN                        1906
[66 l/100 km (city)]          1
[6.9 l/100 km (city)]       215
[9.5 l/100 km (city)]         2
4.7 l/100 km (comb)          47
[3.5 l/100 km (city)]       230
4.8 l/100 km (comb)          23
[1 l/100 km (city)]           2
[6.5 kg/100 km (city)]        1
4.2 l/100 km (comb)          27
[9.2 l/100 km (city)]        31
4.4 l/100 km (comb)          28
[9.7 l/100 km (city)]         1
5.1 l/100 km (comb)          27
4.5 l/100 km (comb)          12
[0 l/100 km (city)]           6
[4.3 l/100 km (city)]       512
6 l/100 km (comb)            53
5.3 l/100 km (comb)           5
[7.4 l/100 km (city)]       170
[10.5 kg/100 km (city)]       1
[7.6 l/100 km (city)]       227
[64 l/100 km (city)]          1
[7.5 l/100 km (city)]       217
[6.8 kg/100 km (city)]        1
[8.6 l/100 km (city)]        27
[7.9 l/100 km (city)]        77
[8.9 l/100 km (city)]         4
1.6 l/100 km (comb)           3
[7.3 l/1

In [159]:
consumption1 = oto.Consumption.str[1].str.extract("(\d.\d|\d)")

In [160]:
consumption1.head()

0
0  NaN
1  NaN
2  NaN
3  NaN
4  NaN

In [161]:
consumption1[0].value_counts(dropna = False)

NaN    15069
5.4      107
5.9       61
6         53
5.6       50
4.7       47
4.9       45
6.3       40
6.1       40
5.7       40
5.5       38
6.2       32
5         32
6.6       29
4.4       28
4.2       27
5.1       27
5.2       25
4.8       23
5.8       22
4.3       12
4.5       12
6.4       11
6.7       10
6.5        7
4.6        6
6.9        6
5.3        5
7.4        4
1.6        3
6.8        2
7          1
4.1        1
3.9        1
4          1
7.9        1
8.6        1
Name: 0, dtype: int64

In [162]:
consumption1[0].value_counts().sum()

850

In [163]:
oto["consumption_comb"].value_counts(dropna = False)

NaN    2883
3.9     732
4       716
5.4     663
5.1     630
4.4     595
3.8     585
5.6     568
4.7     555
4.8     523
5       520
4.5     511
5.2     429
4.6     420
4.2     408
5.3     375
3.7     369
4.9     348
5.5     342
4.1     341
5.9     308
3.3     307
5.7     302
4.3     295
3.5     288
6       278
3.6     194
6.2     184
5.8     142
6.3     141
6.1     135
6.8     134
6.6     119
3.4     106
3        73
6.4      64
7.4      62
7.1      38
1        37
6.5      36
6.7      33
3.2      25
6.9      21
8.3      20
7.6      14
7         9
3.1       7
7.8       6
7.2       6
8         5
8.6       3
8.7       3
7.3       2
0         2
7.9       2
8.1       2
1.2       1
9.1       1
7.5       1
Name: consumption_comb, dtype: int64

In [164]:
oto.consumption_comb.fillna(consumption1[0]).value_counts(dropna = False)

NaN    2033
5.4     770
3.9     733
4       717
5.1     657
4.4     623
5.6     618
4.7     602
3.8     585
5       552
4.8     546
4.5     523
5.2     454
4.2     435
4.6     426
4.9     393
5.3     380
5.5     380
5.9     369
3.7     369
5.7     342
4.1     342
6       331
3.3     307
4.3     307
3.5     288
6.2     216
3.6     194
6.3     181
6.1     175
5.8     164
6.6     148
6.8     136
3.4     106
6.4      75
3        73
7.4      66
6.7      43
6.5      43
7.1      38
1        37
6.9      27
3.2      25
8.3      20
7.6      14
7        10
3.1       7
7.2       6
7.8       6
8         5
8.6       4
1.6       3
7.9       3
8.7       3
7.3       2
0         2
8.1       2
9.1       1
7.5       1
1.2       1
Name: consumption_comb, dtype: int64

In [165]:
oto.consumption_comb.fillna(consumption1[0], inplace = True)

In [166]:
oto.consumption_comb.value_counts(dropna = False)

NaN    2033
5.4     770
3.9     733
4       717
5.1     657
4.4     623
5.6     618
4.7     602
3.8     585
5       552
4.8     546
4.5     523
5.2     454
4.2     435
4.6     426
4.9     393
5.3     380
5.5     380
5.9     369
3.7     369
5.7     342
4.1     342
6       331
3.3     307
4.3     307
3.5     288
6.2     216
3.6     194
6.3     181
6.1     175
5.8     164
6.6     148
6.8     136
3.4     106
6.4      75
3        73
7.4      66
6.7      43
6.5      43
7.1      38
1        37
6.9      27
3.2      25
8.3      20
7.6      14
7        10
3.1       7
7.2       6
7.8       6
8         5
8.6       4
1.6       3
7.9       3
8.7       3
7.3       2
0         2
8.1       2
9.1       1
7.5       1
1.2       1
Name: consumption_comb, dtype: int64

In [167]:
oto.consumption_comb.isnull().sum()*100/oto.consumption_comb.shape[0]

12.770902694892895

In [168]:
oto["Consumption"].str[-2].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                        1906
[5 l/100 km (city)]         642
[5.8 l/100 km (city)]       597
[4.5 l/100 km (city)]       577
[]                          516
                           ... 
[19.9 l/100 km (city)]        1
7 l/100 km (country)          1
[10.5 kg/100 km (city)]       1
6.1 l/100 km (country)        1
[4.4 kg/100 km (city)]        1
Name: Consumption, Length: 121, dtype: int64

In [169]:
oto["Consumption"].str[1].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                       1906
[5 l/100 km (city)]        642
[5.8 l/100 km (city)]      597
[4.5 l/100 km (city)]      577
[]                         516
                          ... 
4.1 l/100 km (comb)          1
[19.9 l/100 km (city)]       1
[6.8 kg/100 km (city)]       1
[9 l/100 km (city)]          1
[4.4 kg/100 km (city)]       1
Name: Consumption, Length: 130, dtype: int64

In [170]:
oto["Consumption"].str[-2].str[0].value_counts(dropna = False)

NaN                      2422
5 l/100 km (city)         642
5.8 l/100 km (city)       597
4.5 l/100 km (city)       577
4                         532
                         ... 
10.5 kg/100 km (city)       1
16.1 l/100 km (city)        1
7                           1
4.4 kg/100 km (city)        1
9.7 l/100 km (city)         1
Name: Consumption, Length: 99, dtype: int64

In [171]:
oto["Consumption"].str[-2].str[0].unique()

array(['4.3 l/100 km (city)', '7.1 l/100 km (city)',
       '4.4 l/100 km (city)', '4.6 l/100 km (city)',
       '4.2 l/100 km (city)', nan, '6.2 l/100 km (city)',
       '5 l/100 km (city)', '5.5 l/100 km (city)', '5.4 l/100 km (city)',
       '3.8 l/100 km (city)', '5.2 l/100 km (city)', '3 l/100 km (city)',
       '4 l/100 km (city)', '3.9 l/100 km (city)', '4.1 l/100 km (city)',
       '3', '4.7 l/100 km (city)', '6.3 l/100 km (city)',
       '6.7 l/100 km (city)', '5.6 l/100 km (city)',
       '4.8 l/100 km (city)', '6.6 l/100 km (city)',
       '4.5 l/100 km (city)', '5.8 l/100 km (city)', '4',
       '7.4 l/100 km (city)', '6.1 l/100 km (city)',
       '3.7 l/100 km (city)', '5.1 l/100 km (city)',
       '19.9 l/100 km (city)', '6.4 l/100 km (city)',
       '8.2 l/100 km (city)', '6 l/100 km (city)', '6.5 l/100 km (city)',
       '5.9 l/100 km (city)', '8 l/100 km (city)', '62 l/100 km (city)',
       '6.8 l/100 km (city)', '7.5 l/100 km (city)',
       '3.5 l/100 km (city)', '5

In [172]:
oto["Consumption"].str[-2].str[0].str.extract("(\d.\d|\d)")[0].value_counts(dropna = False)

NaN    2436
5       858
4       836
5.8     600
4.5     580
       ... 
9.5       2
8.8       2
3.6       2
9         1
9.7       1
Name: 0, Length: 70, dtype: int64

In [173]:
consumption_city = oto["Consumption"].str[-2].str[0].str.extract("(\d.\d|\d)")

In [174]:
consumption_city = pd.to_numeric(consumption_city[0])

In [175]:
consumption_city

0        4.3
1        7.1
2        4.4
3        4.3
4        4.6
        ... 
15914    6.2
15915    6.0
15916    6.2
15917    6.2
15918    8.7
Name: 0, Length: 15919, dtype: float64

Let's take a look at the "country"

In [176]:
oto["Consumption"].str[-1].str[0].unique()

array(['3.5 l/100 km (country)', '4.7 l/100 km (country)',
       '3.4 l/100 km (country)', '3.8 l/100 km (country)',
       '3.1 l/100 km (country)', nan, '3.6 l/100 km (country)',
       '4.2 l/100 km (country)', '3.7 l/100 km (country)',
       '3.9 l/100 km (country)', '3.3 l/100 km (country)',
       '3 l/100 km (country)', '\n', '4.4 l/100 km (country)',
       '4 l/100 km (country)', '4.3 l/100 km (country)',
       '4.9 l/100 km (country)', '4.1 l/100 km (country)',
       '4.5 l/100 km (country)', '3.2 l/100 km (country)',
       '10.3 l/100 km (country)', '5.1 l/100 km (country)',
       '6.7 l/100 km (country)', '6.3 l/100 km (country)',
       '4.8 l/100 km (country)', '44 l/100 km (country)',
       '5.4 l/100 km (country)', '4.6 l/100 km (country)',
       '4.6 kg/100 km (country)', '2.9 kg/100 km (country)',
       '2.8 kg/100 km (country)', '5.6 l/100 km (country)',
       '6.6 l/100 km (country)', '6 l/100 km (country)',
       '6.5 l/100 km (country)', '4.5 kg/100 km 

In [177]:
oto['Consumption'].str[-1].str[0].value_counts(dropna = False)

NaN                       2362
4.2 l/100 km (country)    1101
3.7 l/100 km (country)    1059
\n                         850
4.4 l/100 km (country)     829
                          ... 
6.9 l/100 km (country)       1
7.6 l/100 km (country)       1
42 l/100 km (country)        1
1 l/100 km (country)         1
3 kg/100 km (country)        1
Name: Consumption, Length: 65, dtype: int64

In [178]:
oto['Consumption'].str[-1].str[0].str.extract('(\d.\d|\d)')[0].value_counts(dropna = False)

NaN    3212
4.2    1101
3.7    1059
4.4     829
4.5     789
3.8     775
3.9     759
4.1     569
4.7     562
4       560
3.5     525
4.3     496
3.6     486
3.1     481
3.3     456
4.6     446
4.9     410
3.4     353
4.8     289
5.3     227
5.1     215
5.7     191
5.4     190
3.2     180
3       146
5.6     131
5       106
5.2      84
6.3      49
6        35
1        34
5.5      30
5.8      30
7.7      20
6.6      19
2.9      16
6.4      15
2.8       9
0         9
6.5       4
7.3       4
7.1       3
7         2
6.7       2
7.8       2
5.9       2
6.9       2
8.6       1
2         1
6.1       1
8         1
7.6       1
Name: 0, dtype: int64

In [179]:
consumption_country = oto['Consumption'].str[-1].str[0].str.extract('(\d.\d|\d)')

In [180]:
consumption_country = pd.to_numeric(consumption_country[0])

In [181]:
consumption_country

0        3.5
1        4.7
2        3.4
3        3.5
4        3.8
        ... 
15914    4.7
15915    NaN
15916    4.7
15917    4.7
15918    5.7
Name: 0, Length: 15919, dtype: float64

In [182]:
consumption_city

0        4.3
1        7.1
2        4.4
3        4.3
4        4.6
        ... 
15914    6.2
15915    6.0
15916    6.2
15917    6.2
15918    8.7
Name: 0, Length: 15919, dtype: float64

In [183]:
(consumption_city + consumption_country) / 2

0        3.90
1        5.90
2        3.90
3        3.90
4        4.20
         ... 
15914    5.45
15915     NaN
15916    5.45
15917    5.45
15918    7.20
Name: 0, Length: 15919, dtype: float64

In [184]:
consumption2 = (consumption_city + consumption_country) / 2

In [185]:
consumption2.value_counts(dropna = False)

NaN     3283
3.90     610
5.65     498
4.75     497
4.10     439
        ... 
7.70       1
7.25       1
7.45       1
7.20       1
7.35       1
Name: 0, Length: 139, dtype: int64

In [186]:
oto.consumption_comb.fillna(consumption2).value_counts(dropna = False)

NaN     1925
5.4      770
3.9      733
4        717
5.1      657
        ... 
9.1        1
1.2        1
4.5        1
4.55       1
5.8        1
Name: consumption_comb, Length: 70, dtype: int64

In [187]:
oto.consumption_comb.fillna(consumption2, inplace = True)

In [188]:
oto.consumption_comb.value_counts(dropna = False)

NaN     1925
5.4      770
3.9      733
4        717
5.1      657
        ... 
9.1        1
1.2        1
4.5        1
4.55       1
5.8        1
Name: consumption_comb, Length: 70, dtype: int64

##### 'Gearing Type'

In [189]:
# Examining Gearing Type new column
print('Checking Gearing Type new column')
print('--------------------------')
print(oto['Gearing Type'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Gearing Type'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Gearing Type'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Gearing Type'].dtype,'\n\n')

Checking Gearing Type new column
--------------------------
0        [\n, Automatic, \n]
1        [\n, Automatic, \n]
2        [\n, Automatic, \n]
3        [\n, Automatic, \n]
4        [\n, Automatic, \n]
                ...         
15914    [\n, Automatic, \n]
15915    [\n, Automatic, \n]
15916    [\n, Automatic, \n]
15917    [\n, Automatic, \n]
15918    [\n, Automatic, \n]
Name: Gearing Type, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n, Manual, \n]            8153
[\n, Automatic, \n]         7297
[\n, Semi-automatic, \n]     469
Name: Gearing Type, dtype: int64 


Number of missing values
--------------------------
0 


Data type
--------------------------
object 




In [190]:
oto['Gearing Type'].str[1].value_counts()

Manual            8153
Automatic         7297
Semi-automatic     469
Name: Gearing Type, dtype: int64

In [191]:
oto["gear_type"] = oto['Gearing Type'].str[1]

In [192]:
oto.gear_type.head()

0    Automatic
1    Automatic
2    Automatic
3    Automatic
4    Automatic
Name: gear_type, dtype: object

##### 'Drive chain'

In [193]:
# Examining Drive chain new column
print('Checking Drive chain new column')
print('--------------------------')
print(oto['Drive chain'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Drive chain'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Drive chain'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Drive chain'].dtype,'\n\n')

Checking Drive chain new column
--------------------------
0        [\nfront\n]
1        [\nfront\n]
2        [\nfront\n]
3                NaN
4        [\nfront\n]
            ...     
15914    [\nfront\n]
15915    [\nfront\n]
15916    [\nfront\n]
15917    [\nfront\n]
15918      [\n4WD\n]
Name: Drive chain, Length: 15919, dtype: object 


Number of each values
--------------------------
[\nfront\n]    8886
NaN            6858
[\n4WD\n]       171
[\nrear\n]        4
Name: Drive chain, dtype: int64 


Number of missing values
--------------------------
6858 


Data type
--------------------------
object 




In [194]:
oto["drive_chain"] = oto["Drive chain"].str[0].str.strip("\n")

In [195]:
oto.drive_chain.value_counts(dropna = False)

front    8886
NaN      6858
4WD       171
rear        4
Name: drive_chain, dtype: int64

##### 'Model Code'

In [196]:
# Examining Model Code new column
print('Checking Model Code new column')
print('--------------------------')
print(oto['Model Code'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Model Code'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Model Code'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Model Code'].dtype,'\n\n')

Checking Model Code new column
--------------------------
0        [\n0588/BDF\n]
1        [\n0588/BCY\n]
2                   NaN
3                   NaN
4        [\n0588/BDF\n]
              ...      
15914               NaN
15915    [\n0000/000\n]
15916               NaN
15917               NaN
15918    [\n3333/BHJ\n]
Name: Model Code, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN               10941
[\n0035/BCB\n]      268
[\n0588/BNO\n]      245
[\n0588/BDB\n]      206
[\n0588/BHX\n]      188
                  ...  
[\n1844/AEN\n]        1
[\n0588/AVR\n]        1
[\n0035/AFF\n]        1
[\n1844/AFM\n]        1
[\n0035/AVN\n]        1
Name: Model Code, Length: 233, dtype: int64 


Number of missing values
--------------------------
10941 


Data type
--------------------------
object 




In [197]:
oto["Model Code"].str[0].str.strip("\n")

0        0588/BDF
1        0588/BCY
2             NaN
3             NaN
4        0588/BDF
           ...   
15914         NaN
15915    0000/000
15916         NaN
15917         NaN
15918    3333/BHJ
Name: Model Code, Length: 15919, dtype: object

In [198]:
oto.drop("Model Code", axis = 1, inplace = True)

##### 'Body Color'

In [199]:
# Examining Body Color new column
print('Checking Body Color new column')
print('--------------------------')
print(oto['Body Color'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Body Color'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Body Color'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Body Color'].dtype,'\n\n')

Checking Body Color new column
--------------------------
0        [\n, Black, \n]
1          [\n, Red, \n]
2        [\n, Black, \n]
3        [\n, Brown, \n]
4        [\n, Black, \n]
              ...       
15914     [\n, Grey, \n]
15915     [\n, Grey, \n]
15916    [\n, White, \n]
15917     [\n, Grey, \n]
15918     [\n, Grey, \n]
Name: Body Color, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n, Black, \n]     3745
[\n, Grey, \n]      3505
[\n, White, \n]     3406
[\n, Silver, \n]    1647
[\n, Blue, \n]      1431
[\n, Red, \n]        957
NaN                  597
[\n, Brown, \n]      289
[\n, Green, \n]      154
[\n, Beige, \n]      108
[\n, Yellow, \n]      51
[\n, Violet, \n]      18
[\n, Bronze, \n]       6
[\n, Orange, \n]       3
[\n, Gold, \n]         2
Name: Body Color, dtype: int64 


Number of missing values
--------------------------
597 


Data type
--------------------------
object 




In [200]:
oto["Body Color"].str[1].value_counts(dropna = False)

Black     3745
Grey      3505
White     3406
Silver    1647
Blue      1431
Red        957
NaN        597
Brown      289
Green      154
Beige      108
Yellow      51
Violet      18
Bronze       6
Orange       3
Gold         2
Name: Body Color, dtype: int64

In [201]:
oto['Body_Color'] = oto['Body Color'].str[1].str.strip()
oto.Body_Color

0        Black
1          Red
2        Black
3        Brown
4        Black
         ...  
15914     Grey
15915     Grey
15916    White
15917     Grey
15918     Grey
Name: Body_Color, Length: 15919, dtype: object

In [202]:
oto.Body_Color.fillna(method = "bfill", inplace = True)

In [203]:
oto.Body_Color.value_counts(dropna = False)

Black     3888
Grey      3638
White     3540
Silver    1687
Blue      1524
Red        989
Brown      299
Green      163
Beige      108
Yellow      53
Violet      18
Bronze       7
Orange       3
Gold         2
Name: Body_Color, dtype: int64

##### 'Body Color Original'

In [204]:
# Examining Body Color Original new column
print('Checking Body Color Original new column')
print('--------------------------')
print(oto['Body Color Original'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Body Color Original'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Body Color Original'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Body Color Original'].dtype,'\n\n')

Checking Body Color Original new column
--------------------------
0                 [\nMythosschwarz\n]
1                                 NaN
2        [\nmythosschwarz metallic\n]
3                                 NaN
4        [\nMythosschwarz Metallic\n]
                     ...             
15914              [\nGrigio scuro\n]
15915       [\nStahl-Grau Metallic\n]
15916               [\narktis-weiß\n]
15917                    [\nGrigio\n]
15918    [\nTitanium-Grau Metallic\n]
Name: Body Color Original, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                             3759
[\nOnyx Schwarz\n]               338
[\nBianco\n]                     282
[\nMythosschwarz Metallic\n]     238
[\nBrillantschwarz\n]            216
                                ... 
[\nBianca - Tetto Nero\n]          1
[\ndezir rot\n]                    1
[\nnero/tetto argento met\n]       1
[\nPython Yellow Metallic\n]       1
[\nkarbongrau\n]                   1


In [205]:
oto.drop("Body Color Original", axis = 1, inplace = True)

##### 'CO2 Emission'

In [206]:
# Examining CO2 Emission new column
print('Checking CO2 Emission new column')
print('--------------------------')
print(oto['CO2 Emission'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['CO2 Emission'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['CO2 Emission'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['CO2 Emission'].dtype,'\n\n')

Checking CO2 Emission new column
--------------------------
0         [\n99 g CO2/km (comb)\n]
1        [\n129 g CO2/km (comb)\n]
2         [\n99 g CO2/km (comb)\n]
3         [\n99 g CO2/km (comb)\n]
4        [\n109 g CO2/km (comb)\n]
                   ...            
15914    [\n139 g CO2/km (comb)\n]
15915    [\n168 g CO2/km (comb)\n]
15916    [\n139 g CO2/km (comb)\n]
15917    [\n139 g CO2/km (comb)\n]
15918    [\n153 g CO2/km (comb)\n]
Name: CO2 Emission, Length: 15919, dtype: object 


Number of each values
--------------------------
NaN                            1808
[\n120 g CO2/km (comb)\n]       740
[[], [], []]                    628
[\n99 g CO2/km (comb)\n]        545
[\n97 g CO2/km (comb)\n]        537
                               ... 
[\n193 g CO2/km (comb)\n]         1
[\n171 g CO2/km (comb)\n]         1
[\n990 g CO2/km (comb)\n]         1
[\n1,060 g CO2/km (comb)\n]       1
[\n183 g CO2/km (comb)\n]         1
Name: CO2 Emission, Length: 124, dtype: int64 


Number of

In [207]:
oto["CO2 Emission"].str[0].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                           1808
\n120 g CO2/km (comb)\n        740
[]                             628
\n99 g CO2/km (comb)\n         545
\n97 g CO2/km (comb)\n         537
                              ... 
\n183 g CO2/km (comb)\n          1
\n14,457 g CO2/km (comb)\n       1
\n331 g CO2/km (comb)\n          1
\n184 g CO2/km (comb)\n          1
\n45 g CO2/km (comb)\n           1
Name: CO2 Emission, Length: 124, dtype: int64

In [208]:
oto['CO2 Emission'].str[0].str.strip('\n').value_counts(dropna = False).sample(55)

141 g CO2/km (comb)       156
100 g CO2/km (comb)        36
45 g CO2/km (comb)          1
167 g CO2/km (comb)         2
136 g CO2/km (comb)       145
112 g CO2/km (comb)       171
91 g CO2/km (comb)         31
129 g CO2/km (comb)       213
114 g CO2/km (comb)       382
84 g CO2/km (comb)          2
177 g CO2/km (comb)         1
190 g CO2/km (comb)         1
107 g CO2/km (comb)       362
103 g CO2/km (comb)       445
118 g CO2/km (comb)       270
104 g CO2/km (comb)       501
199 g CO2/km (comb)         2
990 g CO2/km (comb)         1
187 g CO2/km (comb)        26
168 g CO2/km (comb)        58
93 g CO2/km (comb)         66
131 g CO2/km (comb)        48
151 g CO2/km (comb)        34
12,087 g CO2/km (comb)      3
128 g CO2/km (comb)       329
184 g CO2/km (comb)         1
82 g CO2/km (comb)         25
120 g CO2/km (comb)       740
14 g CO2/km (comb)          1
193 g CO2/km (comb)         1
331 g CO2/km (comb)         1
160 g CO2/km (comb)         1
253 g CO2/km (comb)         1
146 g CO2/

In [209]:
oto['CO2 Emission'].str[0].str.strip('\n').value_counts(dropna = False).sample(55)

189 g CO2/km (comb)        19
98 g CO2/km (comb)        151
115 g CO2/km (comb)        86
130 g CO2/km (comb)       180
1,060 g CO2/km (comb)       1
143 g CO2/km (comb)       171
155 g CO2/km (comb)         8
186 g CO2/km (comb)        30
137 g CO2/km (comb)       133
146 g CO2/km (comb)        36
131 g CO2/km (comb)        48
158 g CO2/km (comb)        17
188 g CO2/km (comb)         7
181 g CO2/km (comb)         1
183 g CO2/km (comb)         1
36 g CO2/km (comb)          3
194 g CO2/km (comb)         3
191 g CO2/km (comb)         2
1 g CO2/km (comb)           1
168 g CO2/km (comb)        58
142 g CO2/km (comb)        58
175 g CO2/km (comb)         8
135 g CO2/km (comb)       202
170 g CO2/km (comb)        10
150 g CO2/km (comb)       174
149 g CO2/km (comb)       117
156 g CO2/km (comb)        14
141 g CO2/km (comb)       156
125 g CO2/km (comb)       132
132 g CO2/km (comb)       100
NaN                      2436
253 g CO2/km (comb)         1
117 g CO2/km (comb)       254
174 g CO2/

In [210]:
oto["CO2 Emission"].str[0].str.strip("\n").str.replace(",", "").value_counts(dropna = False).sample(55)

103 g CO2/km (comb)    445
14 g CO2/km (comb)       1
104 g CO2/km (comb)    501
127 g CO2/km (comb)    257
131 g CO2/km (comb)     48
102 g CO2/km (comb)    477
45 g CO2/km (comb)       1
181 g CO2/km (comb)      1
172 g CO2/km (comb)     25
152 g CO2/km (comb)     28
105 g CO2/km (comb)    202
168 g CO2/km (comb)     58
155 g CO2/km (comb)      8
125 g CO2/km (comb)    132
122 g CO2/km (comb)     83
91 g CO2/km (comb)      31
115 g CO2/km (comb)     86
108 g CO2/km (comb)    362
89 g CO2/km (comb)      19
88 g CO2/km (comb)      15
239 g CO2/km (comb)      1
154 g CO2/km (comb)     40
136 g CO2/km (comb)    145
130 g CO2/km (comb)    180
98 g CO2/km (comb)     151
144 g CO2/km (comb)     40
93 g CO2/km (comb)      66
95 g CO2/km (comb)     161
124 g CO2/km (comb)    372
156 g CO2/km (comb)     14
160 g CO2/km (comb)      1
51 g CO2/km (comb)       1
191 g CO2/km (comb)      2
132 g CO2/km (comb)    100
111 g CO2/km (comb)    237
0 g CO2/km (comb)        2
197 g CO2/km (comb)      4
1

In [211]:
oto['CO2 Emission'].str[0].str.strip('\n').str.replace(",", "").unique()

array(['99 g CO2/km (comb)', '129 g CO2/km (comb)', '109 g CO2/km (comb)',
       '92 g CO2/km (comb)', '98 g CO2/km (comb)', '97 g CO2/km (comb)',
       nan, '105 g CO2/km (comb)', '112 g CO2/km (comb)',
       '103 g CO2/km (comb)', '102 g CO2/km (comb)', '95 g CO2/km (comb)',
       '104 g CO2/km (comb)', '91 g CO2/km (comb)', '94 g CO2/km (comb)',
       '117 g CO2/km (comb)', '123 g CO2/km (comb)',
       '106 g CO2/km (comb)', '108 g CO2/km (comb)',
       '121 g CO2/km (comb)', '107 g CO2/km (comb)',
       '101 g CO2/km (comb)', '113 g CO2/km (comb)',
       '137 g CO2/km (comb)', '100 g CO2/km (comb)',
       '116 g CO2/km (comb)', '114 g CO2/km (comb)',
       '118 g CO2/km (comb)', '331 g CO2/km (comb)',
       '115 g CO2/km (comb)', '119 g CO2/km (comb)', '90 g CO2/km (comb)',
       '136 g CO2/km (comb)', '134 g CO2/km (comb)',
       '110 g CO2/km (comb)', '111 g CO2/km (comb)',
       '120 g CO2/km (comb)', '89 g CO2/km (comb)', '142 g CO2/km (comb)',
       '126 g CO2/

In [212]:
pattern = "(\d\d\d\d\d|\d\d\d\d|\d\d\d|\d\d|\d)"

In [213]:
oto["CO2_Emission"] = oto['CO2 Emission'].str[0].str.strip('\n').str.replace(",", "").str.extract(pattern)

In [214]:
oto["CO2_Emission"].value_counts(dropna = False)

NaN    2436
120     740
99      545
97      537
104     501
       ... 
171       1
177       1
45        1
160       1
239       1
Name: CO2_Emission, Length: 123, dtype: int64

In [215]:
oto["CO2_Emission"].unique()

array(['99', '129', '109', '92', '98', '97', nan, '105', '112', '103',
       '102', '95', '104', '91', '94', '117', '123', '106', '108', '121',
       '107', '101', '113', '137', '100', '116', '114', '118', '331',
       '115', '119', '90', '136', '134', '110', '111', '120', '89', '142',
       '126', '122', '128', '127', '138', '130', '125', '85', '124',
       '152', '88', '189', '194', '149', '153', '188', '36', '1060', '96',
       '990', '146', '135', '158', '12087', '141', '172', '154', '150',
       '167', '174', '93', '133', '131', '145', '147', '156', '87', '5',
       '148', '139', '151', '144', '168', '160', '170', '80', '132',
       '155', '14', '159', '0', '143', '140', '82', '12324', '84', '165',
       '51', '157', '169', '166', '253', '164', '175', '190', '161',
       '239', '197', '184', '14457', '199', '13983', '187', '181', '186',
       '177', '180', '162', '45', '171', '183', '1', '191', '193'],
      dtype=object)

let's fill missing values using median.

In [216]:
oto.CO2_Emission.median()

116.0

In [217]:
oto.CO2_Emission.fillna(oto.CO2_Emission.median(), inplace = True)

In [218]:
oto['CO2_Emission'].value_counts(dropna=False)

116.0    2436
120       740
99        545
97        537
104       501
         ... 
171         1
177         1
45          1
160         1
239         1
Name: CO2_Emission, Length: 123, dtype: int64

##### 'Displacement'

In [219]:
# Examining Displacement new column
print('Checking Displacement new column')
print('--------------------------')
print(oto['Displacement'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Displacement'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Displacement'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Displacement'].dtype,'\n\n')

Checking Displacement new column
--------------------------
0        [\n1,422 cc\n]
1        [\n1,798 cc\n]
2        [\n1,598 cc\n]
3        [\n1,422 cc\n]
4        [\n1,422 cc\n]
              ...      
15914    [\n1,997 cc\n]
15915    [\n1,798 cc\n]
15916    [\n1,997 cc\n]
15917    [\n1,997 cc\n]
15918    [\n1,798 cc\n]
Name: Displacement, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n1,598 cc\n]     4761
[\n999 cc\n]       2438
[\n1,398 cc\n]     1314
[\n1,399 cc\n]      749
[\n1,229 cc\n]      677
                   ... 
[\n1,800 cc\n]        1
[\n140 cc\n]          1
[\n15,898 cc\n]       1
[\n1,686 cc\n]        1
[\n1,368 cc\n]        1
Name: Displacement, Length: 78, dtype: int64 


Number of missing values
--------------------------
496 


Data type
--------------------------
object 




In [220]:
oto.Displacement.str[0].str.strip('\n')

0        1,422 cc
1        1,798 cc
2        1,598 cc
3        1,422 cc
4        1,422 cc
           ...   
15914    1,997 cc
15915    1,798 cc
15916    1,997 cc
15917    1,997 cc
15918    1,798 cc
Name: Displacement, Length: 15919, dtype: object

In [221]:
oto['Displacement_cc'] = oto.Displacement.str[0].str.strip('\n')
oto.Displacement_cc

0        1,422 cc
1        1,798 cc
2        1,598 cc
3        1,422 cc
4        1,422 cc
           ...   
15914    1,997 cc
15915    1,798 cc
15916    1,997 cc
15917    1,997 cc
15918    1,798 cc
Name: Displacement_cc, Length: 15919, dtype: object

In [222]:
oto.replace({"Displacement_cc" : {"," : "", " " : "", "cc" : ""}}, regex = True, inplace = True)

In [223]:
oto.Displacement_cc.value_counts(dropna = False).head(44)

1598    4761
999     2438
1398    1314
1399     749
1229     677
1956     670
1461     595
1490     559
NaN      496
1422     467
1197     353
898      351
1395     320
1968     301
1149     288
1618     212
1798     210
1498     196
1600     130
1248     110
1997     103
1364     102
1400      90
998       72
1500      50
2000      46
1000      40
1         36
1998      25
2480      20
1984      18
1200      18
899       11
1397      11
160        6
1499       5
929        5
997        4
1596       4
139        4
900        4
1599       3
1199       3
1396       3
Name: Displacement_cc, dtype: int64

In [224]:
oto.Displacement_cc = pd.to_numeric(oto.Displacement_cc)

oto.Displacement_cc

0        1422.0
1        1798.0
2        1598.0
3        1422.0
4        1422.0
          ...  
15914    1997.0
15915    1798.0
15916    1997.0
15917    1997.0
15918    1798.0
Name: Displacement_cc, Length: 15919, dtype: float64

##### 'Emission Class'

In [225]:
# Examining Emission Class new column
print('Checking Emission Class new column')
print('--------------------------')
print(oto['Emission Class'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Emission Class'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Emission Class'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Emission Class'].dtype,'\n\n')

Checking Emission Class new column
--------------------------
0              [\nEuro 6\n]
1              [\nEuro 6\n]
2              [\nEuro 6\n]
3              [\nEuro 6\n]
4              [\nEuro 6\n]
                ...        
15914                   NaN
15915                   NaN
15916    [\nEuro 6d-TEMP\n]
15917          [\nEuro 6\n]
15918          [\nEuro 6\n]
Name: Emission Class, Length: 15919, dtype: object 


Number of each values
--------------------------
[\nEuro 6\n]          10139
NaN                    3021
[\nEuro 6d-TEMP\n]     1845
[[], [], []]            607
[\nEuro 6c\n]           127
[\nEuro 5\n]             78
[\nEuro 6d\n]            62
[\nEuro 4\n]             40
Name: Emission Class, dtype: int64 


Number of missing values
--------------------------
3021 


Data type
--------------------------
object 




In [226]:
oto['Emission Class'].str[0].str.strip('\n').value_counts(dropna=False)

Euro 6          10139
NaN              3628
Euro 6d-TEMP     1845
Euro 6c           127
Euro 5             78
Euro 6d            62
Euro 4             40
Name: Emission Class, dtype: int64

In [227]:
oto['Emission_Class'] = oto['Emission Class'].str[0].str.strip('\n')

In [228]:
oto.replace({"Emission_Class" : {"Euro 6d-TEMP":"Euro 6", "Euro 6c":"Euro 6", "Euro 6d":"Euro 6"}}, regex = True, inplace = True)

In [229]:
oto.Emission_Class.value_counts(dropna=False)

Euro 6    12173
NaN        3628
Euro 5       78
Euro 4       40
Name: Emission_Class, dtype: int64

##### 'First Registration'

In [230]:
# Examining First Registration new column
print('Checking First Registration new column')
print('--------------------------')
print(oto['First Registration'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['First Registration'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['First Registration'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['First Registration'].dtype,'\n\n')

Checking First Registration new column
--------------------------
0        [\n, 2016, \n]
1        [\n, 2017, \n]
2        [\n, 2016, \n]
3        [\n, 2016, \n]
4        [\n, 2016, \n]
              ...      
15914               NaN
15915    [\n, 2019, \n]
15916    [\n, 2019, \n]
15917    [\n, 2019, \n]
15918    [\n, 2019, \n]
Name: First Registration, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n, 2018, \n]    4522
[\n, 2016, \n]    3674
[\n, 2017, \n]    3273
[\n, 2019, \n]    2853
NaN               1597
Name: First Registration, dtype: int64 


Number of missing values
--------------------------
1597 


Data type
--------------------------
object 




In [231]:
oto['register_age'] = pd.to_numeric(oto['First Registration'].str[1]) 

oto.register_age.value_counts(dropna=False)

2018.0    4522
2016.0    3674
2017.0    3273
2019.0    2853
NaN       1597
Name: register_age, dtype: int64

In [232]:
oto.register_age = 2020 - oto.register_age

We can transform this feature into an "age" column. Let's create a new column called "register_age"

In [233]:
oto.register_age.value_counts(dropna = False)

2.0    4522
4.0    3674
3.0    3273
1.0    2853
NaN    1597
Name: register_age, dtype: int64

##### 'Fuel'

In [234]:
# Examining Fuel new column
print('Checking Fuel new column')
print('--------------------------')
print(oto['Fuel'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Fuel'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Fuel'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Fuel'].dtype,'\n\n')

Checking Fuel new column
--------------------------
0                          [\n, Diesel (Particulate Filter), \n]
1                                             [\n, Gasoline, \n]
2                          [\n, Diesel (Particulate Filter), \n]
3                          [\n, Diesel (Particulate Filter), \n]
4                          [\n, Diesel (Particulate Filter), \n]
                                  ...                           
15914                      [\n, Diesel (Particulate Filter), \n]
15915    [\n, Super 95 / Super Plus 98 (Particulate Filter), \n]
15916                                           [\n, Diesel, \n]
15917                                           [\n, Diesel, \n]
15918                                         [\n, Super 95, \n]
Name: Fuel, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \

In [235]:
oto.Fuel.value_counts(dropna=False).head(40)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Diesel (Particulate Filter), \n]                                                                                  4315
[\n, Super 95, \n]                                                                                                     3338
[\n, Gasoline, \n]                                                                                                     3175
[\n, Diesel, \n]                                                                                                       2984
[\n, Super 95 / Regular/Benzine 91, \n]                                                                                 424
[\n, Regular/Benzine 91, \n]                                                                                            354
[\n, Super E10 95, \n]                                                                                                  331
[\n, Super 95 (Particulate Filter), \n]                                                                                 268
[\n, Sup

In [236]:
oto.Fuel.value_counts(dropna=False).tail(40)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, Super 95 / Regular/Benzine 91 / Super Plus 98, \n]                                                                                     2
[\n, Super E10 95 / Regular/Benzine 91, \n]                                                                                                 2
[\n, Regular/Benzine 91 / Super 95 / Super Plus 98 / Super Plus E10 98 / Super E10 95 / Regular/Benzine E10 91, \n]                         2
[\n, Super Plus 98 / Super 95 / Super Plus E10 98, \n]                                                                                      1
[\n, Super 95 / Super E10 95 / Super Plus E10 98, \n]                                                                                       1
[\n, Regular/Benzine 91 / Super 95 / Super E10 95 / Regular/Benzine E10 91, \n]                                                             1
[\n, Super 95 / Regular/Benzine 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98 / Regular/Benzine E10 91, \n]                         1
[\n, S

In [237]:
oto.Fuel.str[1].value_counts(dropna = False)

Diesel (Particulate Filter)                                                                                  4315
Super 95                                                                                                     3338
Gasoline                                                                                                     3175
Diesel                                                                                                       2984
Super 95 / Regular/Benzine 91                                                                                 424
                                                                                                             ... 
Regular/Benzine 91 / Super 95 / Regular/Benzine E10 91 / Super E10 95 / Super Plus 98 / Super Plus E10 98       1
Super 95 / Super Plus 98 / Regular/Benzine E10 91 / Super Plus E10 98 / Super E10 95 / Regular/Benzine 91       1
Regular/Benzine E10 91 / Super E10 95 / Super Plus E10 98 / Super Plus 98 / Super 95 / R

In [238]:
oto["fuel_new"] = oto.Fuel.str[1]

In [239]:
diesel_bool = oto["fuel_new"].str.contains("diesel", case = False, regex = True)

In [240]:
lpg_bool = oto["fuel_new"].str.contains("lpg|cng|bio|domestic|electric", case = False, regex = True)

In [241]:
oto.loc[diesel_bool, "fuel_new"] = "Diesel"

In [242]:
oto.loc[lpg_bool, "fuel_new"] = "LPG/CNG"

In [243]:
oto.fuel_new.loc[lambda x : x != "Diesel"][lambda x : x != "LPG/CNG"]

1                                             Gasoline
9                                             Gasoline
11                                            Super 95
12                                  Regular/Benzine 91
13                                            Gasoline
                             ...                      
15908                                         Gasoline
15910                           Regular/Benzine E10 91
15913                                         Super 95
15915    Super 95 / Super Plus 98 (Particulate Filter)
15918                                         Super 95
Name: fuel_new, Length: 8550, dtype: object

In [244]:
oto.fuel_new.loc[lambda x : x != "Diesel"][lambda x : x != "LPG/CNG"].index

Int64Index([    1,     9,    11,    12,    13,    14,    18,    21,    22,    24,
            ...
            15900, 15903, 15905, 15906, 15907, 15908, 15910, 15913, 15915, 15918], dtype='int64', length=8550)

In [245]:
benz = list(oto.fuel_new.loc[lambda x : x != "Diesel"][lambda x : x != "LPG/CNG"].index)

In [246]:
oto.fuel_new.iloc[benz] = "Benzine"

In [247]:
oto.fuel_new.value_counts(dropna = False)

Benzine    8550
Diesel     7299
LPG/CNG      70
Name: fuel_new, dtype: int64

##### 'Gears'

In [248]:
# Examining Gears new column
print('Checking Gears new column')
print('--------------------------')
print(oto['Gears'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Gears'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Gears'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Gears'].dtype,'\n\n')

Checking Gears new column
--------------------------
0            NaN
1        [\n7\n]
2            NaN
3        [\n6\n]
4            NaN
          ...   
15914    [\n6\n]
15915    [\n7\n]
15916    [\n6\n]
15917    [\n6\n]
15918        NaN
Name: Gears, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n6\n]     5822
NaN         4712
[\n5\n]     3239
[\n7\n]     1908
[\n8\n]      224
[\n9\n]        6
[\n4\n]        2
[\n3\n]        2
[\n1\n]        2
[\n50\n]       1
[\n2\n]        1
Name: Gears, dtype: int64 


Number of missing values
--------------------------
4712 


Data type
--------------------------
object 




In [249]:
oto["Gears"] = oto.Gears.str[0].str.strip('\n')

In [250]:
oto.Gears.value_counts(dropna = False)

6      5822
NaN    4712
5      3239
7      1908
8       224
9         6
4         2
3         2
1         2
2         1
50        1
Name: Gears, dtype: int64

In [251]:
oto[oto["Gears"] == "50"]

url    make_model              short_description body_type  price             vat     km registration     hp                            Type Previous Owners Next Inspection Inspection new Warranty null         Make           Model     Offer Number First Registration       Body Color      Paint Type   Upholstery Nr. of Doors Nr. of Seats      Gearing Type  Displacement Cylinders Drive chain                Fuel                                                               Consumption               CO2 Emission Emission Class                                                                                              \nComfort & Convenience\n \nEntertainment & Media\n \nExtras\n                                                                                                                                                                                                          \nSafety & Security\n                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          description   Emission Label Gears Country version Previous_Owner1 Previous_Owner  Inspection_New_Bool next_inspection paint_type  country emission_label                                                                                             Comfort&Convenience  cc_Air conditioning  cc_Air suspension  cc_Armrest  cc_Automatic climate control  cc_Auxiliary heating  cc_Cruise control  cc_Electric Starter  cc_Electric tailgate  cc_Electrical side mirrors  \
14495  https://www.autoscout24.com//offers/renault-clio-limited-2018-tce-75-klima-led-gasoline-black-d14154cc-3f6a-4947-87d6-d92768954315  Renault Clio  LIMITED 2018 TCe 75 Klima/LED    Sedans  10798  VAT deductible  10 km      01/2019  56 kW  [, Pre-registered, , Super 95]           \n1\n             NaN            NaN      NaN   []  \nRenault\n  [\n, Clio, \n]  [\nKL_503764\n]     [\n, 2019, \n]  [\n, Black, \n]  [\nMetallic\n]  [\nCloth\n]      [\n5\n]      [\n5\n]  [\n, Manual, \n]  [\n898 cc\n]       NaN         NaN  [\n, Super 95, \n]  [[5.2 l/100 km (comb)], [6.5 l/100 km (city)], [4.4 l/100 km (country)]]  [\n118 g CO2/km (comb)\n]   [\nEuro 6\n]  [Air conditioning, Cruise control, Electrical side mirrors, Leather steering wheel, Power windows, Start-stop system]                     [USB]        NaN  [ABS, Central door lock, Daytime running lights, Driver-side airbag, Electronic stability control, Isofix, LED Daytime Running Lights, Passenger-side airbag, Side airbag, Tire pressure monitoring system, Traction control]  [\n, Sicherheit Airbags:,  , Beifahrerairbag,  , Fahrerairbag,  , Kopfairbags vorne,  , Seitenairbag,  , Sicherheit:,  , ABS,  , Antriebsschlupfregelung (ASR),  , elektr. Stabilitätsprogramm (ESP),  , Geschwindigkeitsbegrenzungsanlage,  , ISOFIX Kindersitzhalterung,  , Kopfstützen im Fonds,  , LED-Tagfahrlicht,  , Reifendruckkontrolle,  , Sommerreifen,  , Tagfahrlicht,  , Traktionskontrolle,  , Komfort:,  , Außenspiegel beheizbar,  , Außenspiegel elektr.,  , Elektr. Fensterheber,  , Fahrersi...  [\n4 (Green)\n]    50   [\nGermany\n]             NaN              1                    0             NaT   Metallic  Germany      4 (Green)  Air conditioning,Cruise control,Electrical side mirrors,Leather steering wheel,Power windows,Start-stop system                    1                  0           0                             0                     0                  1                    0                     0                           1   

       cc_Electrically adjustable seats  cc_Electrically heated windshield  cc_Heads-up display  cc_Heated steering wheel  cc_Hill Holder  cc_Key

In [252]:
oto.Gears.iloc[14495] = "5"

In [253]:
oto.Gears.value_counts(dropna = False)

6      5822
NaN    4712
5      3240
7      1908
8       224
9         6
4         2
3         2
1         2
2         1
Name: Gears, dtype: int64

##### 'Make'

In [254]:
oto.Make.value_counts(dropna = False)

\nOpel\n       7343
\nAudi\n       5712
\nRenault\n    2864
Name: Make, dtype: int64

In [255]:
oto.Make = oto.Make.str.strip('\n')

oto.Make.value_counts()

Opel       7343
Audi       5712
Renault    2864
Name: Make, dtype: int64

##### 'Model'

In [256]:
oto.Model.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, A3, \n]          3097
[\n, A1, \n]          2614
[\n, Insignia, \n]    2598
[\n, Astra, \n]       2526
[\n, Corsa, \n]       2219
[\n, Clio, \n]        1839
[\n, Espace, \n]       991
[\n, Duster, \n]        34
[\n, A2, \n]             1
Name: Model, dtype: int64

In [257]:
oto.Model = oto.Model.str[1] 

oto.Model.value_counts()

A3          3097
A1          2614
Insignia    2598
Astra       2526
Corsa       2219
Clio        1839
Espace       991
Duster        34
A2             1
Name: Model, dtype: int64

##### 'Nr. of Doors'

In [258]:
# Examining Nr. of Doors new column
print('Checking Nr. of Doors new column')
print('--------------------------')
print(oto['Nr. of Doors'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Nr. of Doors'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Nr. of Doors'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Nr. of Doors'].dtype,'\n\n')

Checking Nr. of Doors new column
--------------------------
0        [\n5\n]
1        [\n3\n]
2        [\n4\n]
3        [\n3\n]
4        [\n5\n]
          ...   
15914    [\n5\n]
15915    [\n5\n]
15916    [\n5\n]
15917    [\n5\n]
15918    [\n5\n]
Name: Nr. of Doors, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n5\n]    11575
[\n4\n]     3079
[\n3\n]      832
[\n2\n]      219
NaN          212
[\n7\n]        1
[\n1\n]        1
Name: Nr. of Doors, dtype: int64 


Number of missing values
--------------------------
212 


Data type
--------------------------
object 




In [259]:
oto['Nr. of Doors'].str[0].str.strip('\n').value_counts(dropna=False)

5      11575
4       3079
3        832
2        219
NaN      212
7          1
1          1
Name: Nr. of Doors, dtype: int64

In [260]:
oto['nr_doors'] = oto['Nr. of Doors'].str[0].str.strip('\n') 

oto.nr_doors.value_counts(dropna = False)

5      11575
4       3079
3        832
2        219
NaN      212
7          1
1          1
Name: nr_doors, dtype: int64

##### 'Nr. of Seats'

In [261]:
# Examining Nr. of Seats new column
print('Checking Nr. of Seats new column')
print('--------------------------')
print(oto['Nr. of Seats'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Nr. of Seats'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Nr. of Seats'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Nr. of Seats'].dtype,'\n\n')

Checking Nr. of Seats new column
--------------------------
0        [\n5\n]
1        [\n4\n]
2        [\n4\n]
3        [\n4\n]
4        [\n5\n]
          ...   
15914    [\n5\n]
15915    [\n5\n]
15916    [\n7\n]
15917    [\n7\n]
15918    [\n5\n]
Name: Nr. of Seats, Length: 15919, dtype: object 


Number of each values
--------------------------
[\n5\n]    13336
[\n4\n]     1125
NaN          977
[\n7\n]      362
[\n2\n]      116
[\n6\n]        2
[\n3\n]        1
Name: Nr. of Seats, dtype: int64 


Number of missing values
--------------------------
977 


Data type
--------------------------
object 




In [262]:
oto['Nr. of Seats'].str[0].str.strip('\n').value_counts(dropna = False)

5      13336
4       1125
NaN      977
7        362
2        116
6          2
3          1
Name: Nr. of Seats, dtype: int64

In [263]:
oto['nr_seats'] = oto['Nr. of Seats'].str[0].str.strip('\n')

oto.nr_seats.value_counts(dropna = False)

5      13336
4       1125
NaN      977
7        362
2        116
6          2
3          1
Name: nr_seats, dtype: int64

##### 'Offer Number'

In [264]:
oto["Offer Number"].value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


NaN                       3175
[\nXJ38068\n]               27
[\nHM53619\n]               27
[\nLT67679\n]               27
[\nJV03654\n]               27
                          ... 
[\nE84_474_6130_158\n]       1
[\n101\n]                    1
[\n418394\n]                 1
[\nrv290009\n]               1
[\nG02394\n]                 1
Name: Offer Number, Length: 11441, dtype: int64

In [265]:
oto.drop("Offer Number", axis = 1, inplace = True)

##### 'Type'

In [266]:
# Examining Type new column
print('Checking Type new column')
print('--------------------------')
print(oto['Type'],'\n\n')
print('Number of each values')
print('--------------------------')
print(oto['Type'].value_counts(dropna=False),'\n\n')
print('Number of missing values')
print('--------------------------')
print(oto['Type'].isnull().sum(),'\n\n')
print('Data type')
print('--------------------------')
print(oto['Type'].dtype,'\n\n')

Checking Type new column
--------------------------
0                          [, Used, , Diesel (Particulate Filter)]
1                                             [, Used, , Gasoline]
2                          [, Used, , Diesel (Particulate Filter)]
3                          [, Used, , Diesel (Particulate Filter)]
4                          [, Used, , Diesel (Particulate Filter)]
                                   ...                            
15914                       [, New, , Diesel (Particulate Filter)]
15915    [, Used, , Super 95 / Super Plus 98 (Particulate Filter)]
15916                                 [, Pre-registered, , Diesel]
15917                                 [, Pre-registered, , Diesel]
15918                                [, Demonstration, , Super 95]
Name: Type, Length: 15919, dtype: object 


Number of each values
--------------------------
[, Used, , Diesel (Particulate Filter)]                                                                               

In [267]:
oto.Type.str[1].value_counts(dropna = False)

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: Type, dtype: int64

In [268]:
oto.Type = oto['Type'].str[1]

oto.Type.value_counts(dropna = False)

Used              11096
New                1650
Pre-registered     1364
Employee's car     1011
Demonstration       796
NaN                   2
Name: Type, dtype: int64

##### 'Upholstery'

In [269]:
oto.Upholstery.isnull().sum()/oto.Upholstery.shape[0]*100

23.368302029021923

In [270]:
oto.Upholstery.value_counts(dropna = False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\nCloth, Black\n]           5821
NaN                          3720
[\nPart leather, Black\n]    1121
[\nCloth\n]                  1005
[\nCloth, Grey\n]             891
[\nCloth, Other\n]            639
[\nFull leather, Black\n]     575
[\nBlack\n]                   491
[\nGrey\n]                    273
[\nOther, Other\n]            182
[\nPart leather\n]            140
[\nFull leather\n]            139
[\nFull leather, Brown\n]     116
[\nPart leather, Grey\n]      116
[\nOther, Black\n]            110
[\nFull leather, Other\n]      72
[\nFull leather, Grey\n]       67
[\nPart leather, Other\n]      65
[\nOther\n]                    56
[\nPart leather, Brown\n]      50
[\nalcantara, Black\n]         47
[\nVelour, Black\n]            36
[\nFull leather, Beige\n]      36
[\nCloth, Brown\n]             28
[\nVelour\n]                   16
[\nOther, Grey\n]              15
[\nCloth, Beige\n]             13
[\nCloth, Blue\n]              12
[\nBrown\n]                    12
[\nVelour, Gre

In [271]:
oto.Upholstery = oto.Upholstery.str[0].str.strip('\n')

In [272]:
oto.Upholstery.value_counts(dropna = False)

Cloth, Black           5821
NaN                    3720
Part leather, Black    1121
Cloth                  1005
Cloth, Grey             891
Cloth, Other            639
Full leather, Black     575
Black                   491
Grey                    273
Other, Other            182
Part leather            140
Full leather            139
Part leather, Grey      116
Full leather, Brown     116
Other, Black            110
Full leather, Other      72
Full leather, Grey       67
Part leather, Other      65
Other                    56
Part leather, Brown      50
alcantara, Black         47
Full leather, Beige      36
Velour, Black            36
Cloth, Brown             28
Velour                   16
Other, Grey              15
Cloth, Beige             13
Brown                    12
Cloth, Blue              12
Cloth, White              8
Velour, Grey              8
alcantara, Grey           6
Cloth, Red                5
Other, Yellow             4
Part leather, Red         3
Beige               

##### 'Warranty'

In [273]:
oto.Warranty.isnull().sum()/oto.Warranty.shape[0]*100

34.047364784220115

In [274]:
oto.Warranty.isnull().sum()

5420

In [275]:
oto.Warranty.value_counts(dropna=False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n, \n, \n, 4.9 l/100 km (comb), \n, 6 l/100 km (city), \n, 4.2 l/100 km (country), \n]               1
[\n60 months\n, \n, 6.1 l/100 km (comb), \n, 7.5 l/100 km (city), \n, 5.3 l/100 km (country), \n]      5
[\n48 months\n]                                                                                        3
[\n, \n, \n153 g CO2/km (comb)\n]                                                                      9
[\n72 months\n, \n, 6.1 l/100 km (comb), \n, 7.7 l/100 km (city), \n, 5.2 l/100 km (country), \n]      1
[\n12 months\n, \n115 g CO2/km (comb)\n]                                                               4
[\n60 months\n, \n106 g CO2/km (comb)\n]                                                               1
[\n17 months\n, \n105 g CO2/km (comb)\n]                                                               1
[\n, \n, \n122 g CO2/km (comb)\n]                                                                     10
[\n60 months\n, \n152 g CO2/km (comb)\n]               

In [276]:
oto.Warranty.value_counts(dropna=False).sample(55)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[\n60 months\n, \n118 g CO2/km (comb)\n]                                                              1
[\n6 months\n, \n109 g CO2/km (comb)\n]                                                               1
[\n60 months\n, \n123 g CO2/km (comb)\n]                                                              4
[\n, \n, \n111 g CO2/km (comb)\n]                                                                    38
[\n20 months\n, \nEuro 6\n]                                                                           3
[\n, \n, \n156 g CO2/km (comb)\n]                                                                     5
[\n60 months\n, \n125 g CO2/km (comb)\n]                                                              4
[\n72 months\n, \n133 g CO2/km (comb)\n]                                                              1
[\n, \n, \n137 g CO2/km (comb)\n]                                                                    14
\n72 months\n                                                   

In [277]:
warranty_list = ["".join(item).strip() if type(item) == list else item for item in oto["Warranty"]]

In [278]:
oto["warranty_month"] = pd.DataFrame(warranty_list)

In [279]:
oto.warranty_month.value_counts(dropna = False).sample(55)

24 months\n\n102 g CO2/km (comb)                                                    4
60 months\n\n148 g CO2/km (comb)                                                    1
12 months\n\n123 g CO2/km (comb)                                                    4
60 months\n\n5.6 l/100 km (comb)\n7.2 l/100 km (city)\n4.8 l/100 km (country)       3
15 months\n\n132 g CO2/km (comb)                                                    1
25 months\n\nEuro 6                                                                 4
60 months\n\n125 g CO2/km (comb)                                                    4
24 months\n\n98 g CO2/km (comb)                                                    11
60 months\n\n6 l/100 km (comb)\n7.3 l/100 km (city)\n5.2 l/100 km (country)         1
24 months\n\n4 (Green)                                                             15
48 months\n\n101 g CO2/km (comb)                                                    1
\n6 months\n                                          

In [280]:
oto.warranty_month.value_counts(dropna = False).sample(55)

17 months\n\nEuro 6                                                               1
24 months\n\n6.4 l/100 km (comb)\n8.1 l/100 km (city)\n5.4 l/100 km (country)     1
60 months\n\nEuro 6                                                              67
12 months\n\n104 g CO2/km (comb)                                                 34
47 months\n\n4 (Green)                                                            1
60 months\n\n154 g CO2/km (comb)                                                  2
72 months\n\n140 g CO2/km (comb)                                                  1
12 months\n\n6.1 l/100 km (comb)\n7.5 l/100 km (city)\n5.3 l/100 km (country)     2
36 months\n\n4 (Green)                                                           30
72 months\n\n133 g CO2/km (comb)                                                  1
36 months\n\n111 g CO2/km (comb)                                                  3
92 g CO2/km (comb)                                                          

There are several numeric values in the same line

In order to select months from among the other numeric values, we should use the syntax below.

Firstly, we will select "dd months"

Secondly, we replace all chars other than numeric

In [281]:
oto.warranty_month.str.extract("(\d\d months|\d months)")

0
0            NaN
1            NaN
2            NaN
3            NaN
4            NaN
...          ...
15914  24 months
15915        NaN
15916        NaN
15917        NaN
15918        NaN

[15919 rows x 1 columns]

In [282]:
oto["warranty_month"] = oto.warranty_month.str.extract("(\d\d months|\d months)")

In [283]:
oto.warranty_month.value_counts(dropna = False)

NaN          11066
12 months     2594
24 months     1118
60 months      401
36 months      279
48 months      149
6 months       125
72 months       59
3 months        33
23 months       11
18 months       10
20 months        7
25 months        6
2 months         5
50 months        4
16 months        4
26 months        4
4 months         3
13 months        3
19 months        3
1 months         3
34 months        3
9 months         2
22 months        2
17 months        2
11 months        2
21 months        2
14 months        2
45 months        2
28 months        2
46 months        2
10 months        1
40 months        1
49 months        1
47 months        1
7 months         1
56 months        1
65 months        1
30 months        1
8 months         1
15 months        1
33 months        1
Name: warranty_month, dtype: int64

In [284]:
oto.drop(["Warranty", "warranty_month"], axis = 1, inplace = True)

It has too many missing values so, it will not effect the result if we drop it.

##### 'description'

In [285]:
oto.description.head()

0    [\n, Sicherheit:,  , Deaktivierung für Beifahrer-Airbag,  , ESC mit elektronischer Quersperre,  , Tagfahrlicht,  , Reifendruck-Kontrollanzeige,  , Kopfairbag-System mit Seiten-Airbags vorn,  , Sicherheitslenksäule, Assistenzsysteme:,  , Berganfahrassistent, Komfort:,  , Scheinwerferreinigung,  , Xenon plus inklusive Scheinwerfer-Reinigungsanlage,  , Scheinwerfer-Reinigungsanlage,  , Einparkhilfe hinten,  , Licht-/Regensensor,  , Funkfernbedienung,  , Elektrische Luftzusatzheizung, Interieur:...
1                                                                                                                                                                                                                                                                                                                                                                                                           [\nLangstreckenfahrzeug daher die hohe Kilometerleistung. , Bremsen neu bei 62000 km. , Gut gepfleg

In [286]:
oto.drop('description', axis=1, inplace = True)

##### 'hp'

In [287]:
oto.hp.value_counts(dropna = False)

85 kW     2542
66 kW     2122
81 kW     1402
100 kW    1308
110 kW    1112
          ... 
133 kW       1
195 kW       1
132 kW       1
115 kW       1
123 kW       1
Name: hp, Length: 81, dtype: int64

In [288]:
oto.hp.isnull().sum()

0

In [289]:
oto.hp.value_counts(dropna=False).sample(55)

133 kW       1
101 kW      47
239 kW       1
112 kW       7
155 kW       6
76 kW        4
150 kW       2
119 kW      30
54 kW      276
165 kW     194
53 kW        2
67 kW       40
51 kW      695
132 kW       1
4 kW         1
141 kW      16
60 kW      160
162 kW      98
118 kW     516
88 kW      177
149 kW       3
168 kW       3
90 kW        4
77 kW      345
63 kW        2
70 kW      888
93 kW        3
75 kW        1
115 kW       1
154 kW      39
125 kW     707
103 kW     253
127 kW       2
96 kW       72
143 kW       2
65 kW        4
56 kW      286
80 kW        3
117 kW       6
147 kW     380
71 kW       59
294 kW      18
100 kW    1308
89 kW        2
78 kW       20
184 kW       5
52 kW       22
86 kW        2
1 kW        20
167 kW       2
228 kW       2
- kW        88
92 kW      466
98 kW        3
121 kW     392
Name: hp, dtype: int64

In [290]:
oto.hp.value_counts(dropna=False).sample(55)

191 kW       7
122 kW      35
163 kW       1
110 kW    1112
81 kW     1402
52 kW       22
150 kW       2
135 kW      24
184 kW       5
127 kW       2
78 kW       20
74 kW       81
86 kW        2
137 kW       1
56 kW      286
96 kW       72
44 kW        1
149 kW       3
40 kW        2
54 kW      276
117 kW       6
140 kW       2
118 kW     516
93 kW        3
121 kW     392
98 kW        3
87 kW      232
84 kW        1
82 kW       22
- kW        88
60 kW      160
100 kW    1308
112 kW       7
89 kW        2
167 kW       2
53 kW        2
165 kW     194
132 kW       1
270 kW       2
146 kW      18
123 kW       1
80 kW        3
75 kW        1
90 kW        4
4 kW         1
9 kW         1
1 kW        20
141 kW      16
76 kW        4
164 kW      27
66 kW     2122
55 kW      569
104 kW       8
115 kW       1
168 kW       3
Name: hp, dtype: int64

In [291]:
oto.hp.unique()

array(['66 kW', '141 kW', '85 kW', '70 kW', '92 kW', '112 kW', '60 kW',
       '71 kW', '67 kW', '110 kW', '93 kW', '147 kW', '86 kW', '140 kW',
       '87 kW', '- kW', '81 kW', '82 kW', '135 kW', '132 kW', '100 kW',
       '96 kW', '162 kW', '150 kW', '294 kW', '228 kW', '270 kW',
       '137 kW', '9 kW', '133 kW', '77 kW', '101 kW', '78 kW', '103 kW',
       '1 kW', '74 kW', '118 kW', '84 kW', '88 kW', '80 kW', '76 kW',
       '149 kW', '44 kW', '51 kW', '55 kW', '52 kW', '63 kW', '40 kW',
       '65 kW', '75 kW', '125 kW', '120 kW', '184 kW', '239 kW', '121 kW',
       '143 kW', '191 kW', '89 kW', '195 kW', '127 kW', '122 kW',
       '154 kW', '155 kW', '104 kW', '123 kW', '146 kW', '90 kW', '53 kW',
       '54 kW', '56 kW', '164 kW', '4 kW', '163 kW', '57 kW', '119 kW',
       '165 kW', '117 kW', '115 kW', '98 kW', '168 kW', '167 kW'],
      dtype=object)

In [292]:
oto.replace({"hp" : {" kW" : "", "-" : "0"}}, regex = True, inplace = True)

In [293]:
oto["hp_kw"] = pd.to_numeric(oto.hp)

In [294]:
oto.hp_kw.value_counts(dropna = False)

85     2542
66     2122
81     1402
100    1308
110    1112
       ... 
163       1
123       1
115       1
75        1
239       1
Name: hp_kw, Length: 81, dtype: int64

##### 'km'

In [295]:
oto.km.isnull().sum()

0

In [296]:
oto.km.value_counts(dropna = False)

10 km        1045
- km         1024
1 km          367
5 km          170
50 km         148
             ... 
21,083 km       1
41,961 km       1
22,745 km       1
16,427 km       1
29,877 km       1
Name: km, Length: 6690, dtype: int64

There are "-" values which means NaNs. We can not accept these values as 0 km

In [297]:
oto[oto["km"] == "- km"]["register_age"].value_counts(dropna = False)

NaN    838
1.0    147
2.0     38
3.0      1
Name: register_age, dtype: int64

In [298]:
oto.replace({"km" : {" km" : "", "," : "", "-" : np.nan}}, regex = True, inplace = True)

In [299]:
oto.km = pd.to_numeric(oto.km)

In [300]:
oto.km.value_counts(dropna = False)

10.0       1045
NaN        1024
1.0         367
5.0         170
50.0        148
           ... 
8329.0        1
267.0         1
1060.0        1
73652.0       1
49320.0       1
Name: km, Length: 6690, dtype: int64

##### 'make_model'

In [301]:
oto.make_model.isnull().sum()

0

In [302]:
oto.make_model.value_counts(dropna=False)

Audi A3           3097
Audi A1           2614
Opel Insignia     2598
Opel Astra        2526
Opel Corsa        2219
Renault Clio      1839
Renault Espace     991
Renault Duster      34
Audi A2              1
Name: make_model, dtype: int64

In [303]:
oto.drop(["Make", "Model"], axis = 1, inplace = True)

##### 'null'

In [304]:
oto.null.isnull().sum()

0

In [305]:
oto.null.value_counts(dropna=False)

TypeError: unhashable type: 'list'

Exception ignored in: 'pandas._libs.index.IndexEngine._call_map_locations'
Traceback (most recent call last):
  File "pandas\_libs\hashtable_class_helper.pxi", line 1652, in pandas._libs.hashtable.PyObjectHashTable.map_locations
TypeError: unhashable type: 'list'


[]    15919
Name: null, dtype: int64

In [306]:
oto.drop("null", axis = 1, inplace = True)

##### 'registration'

In [307]:
oto.registration.isnull().sum()

0

In [308]:
oto.registration.value_counts(dropna = False)

-/-        1597
03/2018     695
02/2019     585
05/2018     572
03/2019     543
04/2018     541
01/2019     541
02/2018     539
03/2016     536
06/2018     532
04/2016     532
01/2018     511
04/2019     506
02/2016     472
03/2017     471
05/2016     459
06/2016     452
05/2019     440
06/2017     409
05/2017     404
07/2018     396
04/2017     380
01/2016     376
02/2017     368
01/2017     306
08/2018     285
06/2019     224
07/2017     215
11/2017     180
07/2016     176
10/2016     160
10/2017     154
09/2017     149
11/2016     142
09/2018     141
09/2016     141
12/2016     134
12/2017     123
08/2017     114
11/2018     110
12/2018     103
10/2018      97
08/2016      94
07/2019       6
09/2019       5
11/2019       1
12/2019       1
08/2019       1
Name: registration, dtype: int64

In [309]:
oto.drop("registration", axis = 1, inplace = True)

##### 'short_description'

In [310]:
oto.short_description.isnull().sum()

46

In [311]:
oto.short_description.value_counts(dropna = False)

SPB 1.6 TDI 116 CV S tronic Sport            64
NaN                                          46
1.4 66kW (90CV) Selective                    40
MOVE KLIMA CD USB ALLWETTER BLUETOOTH        38
SPB 30 TDI S tronic Business                 35
                                             ..
1.0 Tfsi 95cv Design                          1
Sportback 1.4 TFSI "S line" S tronic,Navi     1
Initiale Paris dCi 200 EDC                    1
1.6 CDTI Dynamic                              1
Black Edition demowagen automaat              1
Name: short_description, Length: 10002, dtype: int64

In [312]:
oto.drop("short_description", axis = 1, inplace = True)

##### 'url'

In [313]:
oto.url.value_counts(dropna = False)

https://www.autoscout24.com//offers/renault-clio-1-5-dci-90ch-energy-intens-edc-5p-diesel-grey-c704c15f-c14b-4c7b-8e86-7ac1867570b7                1
https://www.autoscout24.com//offers/audi-a1-sportback-sport-advanced-30-tfsi-gasoline-red-938f7eae-92d8-4e4f-92d0-c9bebe30caf8                     1
https://www.autoscout24.com//offers/audi-a1-sportback-1-0tfsi-96pk-adrenalin--navigatie--cru-gasoline-grey-38f49251-cbdf-4965-8c52-07d89bebc378    1
https://www.autoscout24.com//offers/audi-a3-sportback-1-6-tdi-clean-diesel-navi-automatik-diesel-black-234a38c6-4acd-4532-b391-0163e8bf972d        1
https://www.autoscout24.com//offers/opel-corsa-1-4-edition-aut-gasoline-grey-96dacb80-0a4f-42b8-b834-58d28933d44c                                  1
                                                                                                                                                  ..
https://www.autoscout24.com//offers/opel-corsa-e-1-4-at-5t-eu-edition-gasoline-grey-94de029b-7d88-43d0-91e

In [314]:
oto.drop('url', axis = 1, inplace = True)

##### 'vat'

In [315]:
oto.vat.isnull().sum()/oto.vat.shape[0]*100

28.349770714240847

In [316]:
oto.vat.value_counts(dropna = False)

VAT deductible      10980
NaN                  4513
Price negotiable      426
Name: vat, dtype: int64

##### 'price'

This is our target variable which we try to predict..

In [317]:
oto.price.isnull().sum()

0

In [318]:
oto.price.sort_values()

8594        13
8828       120
6066       255
8829       331
8827      4950
         ...  
15828    64332
3587     64900
3649     67600
15826    68320
3648     74600
Name: price, Length: 15919, dtype: int64

In [319]:
oto.price.value_counts(dropna = False)

14990    154
15990    151
10990    139
15900    106
17990    102
        ... 
48490      1
36180      1
40745      1
9545       1
34815      1
Name: price, Length: 2956, dtype: int64

In [320]:
print(list(oto.columns))

['make_model', 'body_type', 'price', 'vat', 'km', 'hp', 'Type', 'Previous Owners', 'Next Inspection', 'Inspection new', 'First Registration', 'Body Color', 'Paint Type', 'Upholstery', 'Nr. of Doors', 'Nr. of Seats', 'Gearing Type', 'Displacement', 'Cylinders', 'Drive chain', 'Fuel', 'Consumption', 'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n', '\nEntertainment & Media\n', '\nExtras\n', '\nSafety & Security\n', 'Emission Label', 'Gears', 'Country version', 'Previous_Owner1', 'Previous_Owner', 'Inspection_New_Bool', 'next_inspection', 'paint_type', 'country', 'emission_label', 'Comfort&Convenience', 'cc_Air conditioning', 'cc_Air suspension', 'cc_Armrest', 'cc_Automatic climate control', 'cc_Auxiliary heating', 'cc_Cruise control', 'cc_Electric Starter', 'cc_Electric tailgate', 'cc_Electrical side mirrors', 'cc_Electrically adjustable seats', 'cc_Electrically heated windshield', 'cc_Heads-up display', 'cc_Heated steering wheel', 'cc_Hill Holder', 'cc_Keyless central door 

now it is time to drop repeated columns we have 

In [321]:
current_clmn = list(oto.columns)

In [322]:
drop_columns = ['Previous Owners', 'Next Inspection', 'Inspection new', 'First Registration', 'Body Color', 'Paint Type', 
 'Nr. of Doors', 'Nr. of Seats', 'Gearing Type', 'Displacement', 'Drive chain', 'Fuel', 'Consumption', 
 'CO2 Emission', 'Emission Class', '\nComfort & Convenience\n', '\nEntertainment & Media\n', '\nExtras\n', 
 '\nSafety & Security\n', 'Emission Label', 'Country version', 'Previous_Owner1', 'Comfort&Convenience', 
 'Entertainment&Media', 'extra', 'Safe&Secure', "hp"]

In [323]:
oto1 = oto.drop(drop_columns, axis = 1)

In [324]:
oto1.shape

(15919, 121)

In [325]:
oto1.columns = oto1.columns.str.lower()

In [326]:
list(oto1.columns)

['make_model',
 'body_type',
 'price',
 'vat',
 'km',
 'type',
 'upholstery',
 'cylinders',
 'gears',
 'previous_owner',
 'inspection_new_bool',
 'next_inspection',
 'paint_type',
 'country',
 'emission_label',
 'cc_air conditioning',
 'cc_air suspension',
 'cc_armrest',
 'cc_automatic climate control',
 'cc_auxiliary heating',
 'cc_cruise control',
 'cc_electric starter',
 'cc_electric tailgate',
 'cc_electrical side mirrors',
 'cc_electrically adjustable seats',
 'cc_electrically heated windshield',
 'cc_heads-up display',
 'cc_heated steering wheel',
 'cc_hill holder',
 'cc_keyless central door lock',
 'cc_leather seats',
 'cc_leather steering wheel',
 'cc_light sensor',
 'cc_lumbar support',
 'cc_massage seats',
 'cc_multi-function steering wheel',
 'cc_navigation system',
 'cc_panorama roof',
 'cc_park distance control',
 'cc_parking assist system camera',
 'cc_parking assist system self-steering',
 'cc_parking assist system sensors front',
 'cc_parking assist system sensors rear'

In [327]:
oto1.to_csv("scout_car_precleaned.csv", index = False)

End of this Project. Next step will be :
    
Handling with Missing Values and Outliers,

Continue to clean DataSet.

Make the DataSet ready to go into ML Models.